### ISSUE TITLE
Branch clean

### ISSUE THREAD

**Issue by pablogs9** [micro-ROS/micro_ros_setup#110]
Please consider removing the following branches if they are not required any more:

- [ ] https://github.com/micro-ROS/micro-ros-build/tree/feature/agent_lite
- [x] https://github.com/micro-ROS/micro-ros-build/tree/feature/mempools_refactor
- [x] https://github.com/micro-ROS/micro-ros-build/tree/feature/parameters
- [x] https://github.com/micro-ROS/micro-ros-build/tree/feature/tof_sensor <- Is this used on the Malaga demo? Should it be a tag?

**Comment by pablogs9** [comment]
@Acuadros95 can we remove the branch and close this?

**Comment by Acuadros95** [comment]
Yes, and maybe we should also delete the rest of old branches:
- [https://github.com/micro-ROS/micro_ros_setup/tree/feature/freertos_host](https://github.com/micro-ROS/micro_ros_setup/tree/feature/freertos_host)
- [https://github.com/micro-ROS/micro_ros_setup/tree/feature/hardware-bridge](https://github.com/micro-ROS/micro_ros_setup/tree/feature/hardware-bridge)

**Comment by pablogs9** [comment]
Not sure about the others. Closing this
