### ISSUE TITLE
Building and flashing the firmware error

### ISSUE THREAD

**Issue by Viplav04** [micro-ROS/micro_ros_setup#15]
after building the client:
ros2 run micro_ros_setup create_firmware_ws.sh
cd firmware/NuttX
tools/configure.sh configs/olimex-stm32-e407/drive_base # FOR EXAMPLE!
cd ../..
ros2 run micro_ros_setup build_firmware.sh
And flashing:
cd firmware/NuttX
scripts/flash.sh olimex-stm32-e407

Flashing the board unsuccessful.
Error: couldn't open nuttx.bin

Please suggest, what to do next. @iluetkeb @BorjaOuterelo

**Comment by iluetkeb** [comment]
`nuttx.bin` should be created as the last step of "build_firmware", so probably something is wrong there. Could you post the output of "build_firmware.sh"? The last 50 lines or so are probably sufficient.

**Comment by Viplav04** [comment]
~/uros_ws$ ros2 run micro_ros_setup build_firmware.sh
Starting >>> ament_package
Starting >>> ament_flake8
Starting >>> ament_cppcheck
Starting >>> gtest_vendor
Starting >>> ament_pep8
Starting >>> osrf_pycommon
Finished <<< ament_package [1.29s]                                                 
Finished <<< ament_flake8 [1.29s]
Finished <<< ament_cppcheck [1.29s]                           
Starting >>> ament_cmake_core
Starting >>> ament_pep257
Finished <<< ament_pep8 [1.31s]
Starting >>> ament_pyflakes
Finished <<< gtest_vendor [1.89s]                                   
Finished <<< osrf_pycommon [1.89s]
Starting >>> gmock_vendor
Finished <<< ament_pep257 [0.64s]
Starting >>> ament_copyright
Starting >>> ament_index_python
Finished <<< ament_pyflakes [1.16s]                                     
Finished <<< ament_cmake_core [1.21s]                                   
Starting >>> ament_cmake_test
Starting >>> ament_cmake_libraries
Starting >>> ament_cmake_export_libraries
Starting >>> ament_cmake_include_directories
Starting >>> ament_cmake_export_definitions
Finished <<< ament_copyright [0.63s]
Starting >>> ament_lint_cmake                                      
Finished <<< ament_index_python [1.00s]                              
Finished <<< gmock_vendor [1.07s]
Starting >>> ament_cmake_export_include_directories
Starting >>> ament_cmake_export_link_flags
Finished <<< ament_cmake_test [0.61s]                                    
Starting >>> ament_cmake_python
Finished <<< ament_cmake_export_libraries [0.61s]
Finished <<< ament_cmake_include_directories [0.61s]
Finished <<< ament_cmake_export_definitions [0.61s]
Finished <<< ament_cmake_libraries [0.66s]
Starting >>> ament_cmake_export_interfaces
Starting >>> ament_cpplint
Starting >>> ament_cmake_export_dependencies                     
Starting >>> ament_cmake_target_dependencies
Finished <<< ament_lint_cmake [0.95s]                            
Finished <<< ament_cmake_export_include_directories [0.57s]
Finished <<< ament_cmake_export_link_flags [0.58s]
Starting >>> ament_cmake_lint_cmake
Starting >>> ament_xmllint
Starting >>> ament_cmake_gtest                                           
Finished <<< ament_cmake_export_interfaces [0.76s]                         
Finished <<< ament_cmake_python [0.85s]
Finished <<< ament_cpplint [0.80s]
Starting >>> ament_lint_auto
Starting >>> ament_clang_format
Starting >>> ament_pclint                                                               
Finished <<< ament_cmake_export_dependencies [0.85s]
Starting >>> ament_cmake_nose
Finished <<< ament_cmake_target_dependencies [1.39s]                                    
Finished <<< ament_xmllint [1.03s]                                             
Starting >>> ament_cmake
Starting >>> ament_cmake_pytest
Finished <<< ament_clang_format [0.68s]
Finished <<< ament_cmake_lint_cmake [1.16s]                                    
Starting >>> ament_cmake_copyright
Finished <<< ament_cmake_gtest [1.16s]
Starting >>> ament_cmake_gmock
Finished <<< ament_lint_auto [0.83s]                                    
Finished <<< ament_cmake_nose [0.85s]                        
Finished <<< ament_cmake [0.31s]
Starting >>> uncrustify_vendor
Starting >>> ament_cmake_auto
Finished <<< ament_cmake_pytest [0.33s]
Finished <<< ament_cmake_gmock [0.24s]                       
Finished <<< ament_cmake_copyright [0.31s]
Starting >>> ament_cmake_cppcheck
Starting >>> ament_cmake_cpplint
Starting >>> ament_cmake_flake8
Starting >>> ament_cmake_pep257
Starting >>> ament_cmake_xmllint
Finished <<< ament_pclint [1.10s]                            
Starting >>> ament_cmake_clang_format
Finished <<< ament_cmake_auto [0.39s]                                          
Starting >>> ament_cmake_pclint
Finished <<< uncrustify_vendor [0.43s]
Starting >>> ament_uncrustify
Finished <<< ament_cmake_cppcheck [0.36s]
Finished <<< ament_cmake_cpplint [0.37s]                                    
Finished <<< ament_cmake_flake8 [0.38s]
Starting >>> ament_cmake_pep8
Starting >>> ament_cmake_pyflakes
Finished <<< ament_cmake_pep257 [0.63s]                                    
Finished <<< ament_cmake_xmllint [0.63s]
Finished <<< ament_cmake_clang_format [0.61s]                                    
Finished <<< ament_cmake_pclint [0.54s]                                    
Finished <<< ament_cmake_pep8 [0.46s]
Finished <<< ament_cmake_pyflakes [0.46s]                        
Finished <<< ament_uncrustify [0.66s]            
Starting >>> ament_cmake_uncrustify
Finished <<< ament_cmake_uncrustify [0.18s]                    
Starting >>> ament_lint_common
Finished <<< ament_lint_common [0.18s]                  
Starting >>> ament_cmake_ros
Starting >>> ament_index_cpp
Finished <<< ament_cmake_ros [0.21s]                                                 
Finished <<< ament_index_cpp [0.38s]                        

Summary: 52 packages finished [7.16s]
Traceback (most recent call last):
  File "/home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py", line 295, in <module>
    main()
  File "/home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py", line 49, in main
    args.additional_extension
  File "/home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py", line 179, in get_commands
    package_dsv_path, prefix, primary_extension, additional_extension)
  File "/home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py", line 224, in process_dsv_file
    additional_extension=additional_extension)
  File "/home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py", line 199, in process_dsv_file
    type_, remainder, prefix)
  File "/home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py", line 262, in handle_dsv_types_except_source
    commands += _prepend_unique_value(env_name, value)
  File "/home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py", line 278, in _prepend_unique_value
    if not env_state[name]:
KeyError: 'PYTHONPATH'

The program does not reach the make command.

**Comment by Viplav04** [comment]
I also tried a manual make and found a compile error , don't think it is related to the above error.

Starting >>> rmw_implementation
--- stderr: rmw_implementation                           
CMake Warning at CMakeLists.txt:19 (find_package):
  Could not find a configuration file for package "poco_vendor" that is
  compatible with requested version "".

  The following configuration files were considered but not accepted:

    /opt/ros/crystal/share/poco_vendor/cmake/poco_vendorConfig.cmake, version: 1.1.1 (64bit)



CMake Warning at CMakeLists.txt:20 (find_package):
  Could not find a configuration file for package "Poco" that is compatible
  with requested version "".

  The following configuration files were considered but not accepted:

    /usr/lib/cmake/Poco/PocoConfig.cmake, version: 1.8.0 (64bit)



CMake Error at /opt/ros/crystal/share/rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp-extras.cmake:6 (find_package):
  Could not find a configuration file for package "fastcdr" that is
  compatible with requested version "".

  The following configuration files were considered but not accepted:

    /opt/ros/crystal/share/fastcdr/cmake/fastcdr-config.cmake, version: 1.0.8 (64bit)

Call Stack (most recent call first):
  /opt/ros/crystal/share/rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cppConfig.cmake:38 (include)
  /opt/ros/crystal/share/rmw_fastrtps_cpp/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /opt/ros/crystal/share/rmw_fastrtps_cpp/cmake/rmw_fastrtps_cppConfig.cmake:38 (include)
  /home/rosteam/uros_ws/firmware/mcu_ws/install/rmw_implementation_cmake/share/rmw_implementation_cmake/cmake/get_default_rmw_implementation.cmake:62 (find_package)
  CMakeLists.txt:28 (get_default_rmw_implementation)


---
Failed   <<< rmw_implementation	[ Exited with code 1 ]

**Comment by Viplav04** [comment]
> `nuttx.bin` should be created as the last step of "build_firmware", so probably something is wrong there. Could you post the output of "build_firmware.sh"? The last 50 lines or so are probably sufficient.

@iluetkeb Shouldn't the build_firmware build the mcu_ws workspace?

**Comment by iluetkeb** [comment]
Okay, because of the PYTHONPATH key error, your build does not actually get to the stage where the firmware is built. It only builds some ament-things which are needed for later.

This works on my machine (tm), so we need your help to figure out what exactly is going wrong.

Please to go the `micro_ros_setup/scripts` directory and edit the `build_firmware.sh` script. The first line currently is `#! /bin/bash`. Edit that to make it `#! /bin/bash -x`. 

After you did that (and rebuilt the micro-ros-build workspace), the next time you will run the `build_firmware.sh` script, it will output which command it is executing. This should help us narrow down which command is failing.

**Comment by Viplav04** [comment]
> Okay, because of the PYTHONPATH key error, your build does not actually get to the stage where the firmware is built. It only builds some ament-things which are needed for later.
> 
> This works on my machine (tm), so we need your help to figure out what exactly is going wrong.
> 
> Please to go the `micro_ros_setup/scripts` directory and edit the `build_firmware.sh` script. The first line currently is `#! /bin/bash`. Edit that to make it `#! /bin/bash -x`.
> 
> After you did that (and rebuilt the micro-ros-build workspace), the next time you will run the `build_firmware.sh` script, it will output which command it is executing. This should help us narrow down which command is failing.

Summary: 52 packages finished [7.32s]
+ set +o nounset
+ . install/setup.bash
++++ dirname install/setup.bash
+++ builtin cd install
+++ pwd
++ COLCON_CURRENT_PREFIX=/home/rosteam/uros_ws/firmware/dev_ws/install
++ _colcon_prefix_chain_bash_source_script /home/rosteam/uros_ws/firmware/dev_ws/install/local_setup.bash
++ '[' -f /home/rosteam/uros_ws/firmware/dev_ws/install/local_setup.bash ']'
++ '[' -n '' ']'
++ . /home/rosteam/uros_ws/firmware/dev_ws/install/local_setup.bash
+++ '[' -z /home/rosteam/uros_ws/firmware/dev_ws/install ']'
+++ _colcon_prefix_bash_COLCON_CURRENT_PREFIX=/home/rosteam/uros_ws/firmware/dev_ws/install
+++ _colcon_prefix_bash_prepend_unique_value COLCON_PREFIX_PATH /home/rosteam/uros_ws/firmware/dev_ws/install
+++ _listname=COLCON_PREFIX_PATH
+++ _value=/home/rosteam/uros_ws/firmware/dev_ws/install
+++ eval '_values="$COLCON_PREFIX_PATH"'
++++ _values=
+++ _colcon_prefix_bash_prepend_unique_value_IFS=' 	
'
+++ IFS=:
+++ _all_values=/home/rosteam/uros_ws/firmware/dev_ws/install
+++ unset _item
+++ IFS=' 	
'
+++ unset _colcon_prefix_bash_prepend_unique_value_IFS
+++ eval export 'COLCON_PREFIX_PATH="/home/rosteam/uros_ws/firmware/dev_ws/install"'
++++ export COLCON_PREFIX_PATH=/home/rosteam/uros_ws/firmware/dev_ws/install
++++ COLCON_PREFIX_PATH=/home/rosteam/uros_ws/firmware/dev_ws/install
+++ unset _all_values
+++ unset _values
+++ unset _value
+++ unset _listname
+++ unset _colcon_prefix_bash_prepend_unique_value
+++ '[' -n '' ']'
+++ _colcon_python_executable=/usr/bin/python3
+++ '[' '!' -f /usr/bin/python3 ']'
++++ /usr/bin/python3 /home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py sh bash
Traceback (most recent call last):
  File "/home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py", line 295, in <module>
    main()
  File "/home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py", line 49, in main
    args.additional_extension
  File "/home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py", line 179, in get_commands
    package_dsv_path, prefix, primary_extension, additional_extension)
  File "/home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py", line 224, in process_dsv_file
    additional_extension=additional_extension)
  File "/home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py", line 199, in process_dsv_file
    type_, remainder, prefix)
  File "/home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py", line 262, in handle_dsv_types_except_source
    commands += _prepend_unique_value(env_name, value)
  File "/home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py", line 278, in _prepend_unique_value
    if not env_state[name]:
KeyError: 'PYTHONPATH'
+++ _colcon_ordered_commands=

This is the new output.

**Comment by iluetkeb** [comment]
Okay, that's really odd. It fails when sourcing the `dev_ws/install/setup.bash`... 

If you have not tried this before, can you please try to remove `firmware/dev_ws/build` and `firmware/dev_ws/install` and then build again?

**Comment by Viplav04** [comment]
Tried and built again, still the same issue. But I can manually source the file.
After sourcing do I go to the nuttx and execute make?
Or am I missing a step in between?

**Comment by iluetkeb** [comment]
You cannot directly compile, because your regular environment configuration will mess things up for the cross-compile. That's mainly what the build_firmware script does: It cleans up your environment and then calls make. Apparently, it does so in a fashion that your setup.bash doesn't like, though.

Try editing the build_firmware.sh again, and remove the `export PYTHONPATH=...` line. It's only there for completeness, and hopefully it should work without it.

**Comment by Viplav04** [comment]
Still no luck, even after deleting and building everything, removing all the export like cmake_prefix path and python_prefix_path frombuild_firmware.sh.

It seems it is sourcing the directories from previous ros2 setup.bash and micro_ros_setup local_setup.bash.

ros2 run micro_ros_setup build_firmware.sh
+ set -e
+ set -o nounset
+ set -o pipefail
+ NUTTX_DIR=firmware/NuttX
+ DEV_WS_DIR=firmware/dev_ws
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 2 ']'
+ PREFIXES_TO_CLEAN=/home/rosteam/uros_ws/install:/opt/ros/crystal
++ clean /opt/ros/crystal/opt/yaml_cpp_vendor/lib:/opt/ros/crystal/opt/rviz_ogre_vendor/lib:/opt/rti.com/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0:/opt/ros/crystal/lib
+++ sed 's/ /:/g'
++++ echo /opt/ros/crystal/opt/yaml_cpp_vendor/lib:/opt/ros/crystal/opt/rviz_ogre_vendor/lib:/opt/rti.com/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0:/opt/ros/crystal/lib
++++ sed 's/:/\n/g'
+++++ echo /home/rosteam/uros_ws/install:/opt/ros/crystal
+++++ sed 's/:/\|/g'
++++ grep -v -E '(/home/rosteam/uros_ws/install|/opt/ros/crystal)'
+++ echo /opt/rti.com/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0
++ echo /opt/rti.com/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0
+ export LD_LIBRARY_PATH=/opt/rti.com/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0
+ LD_LIBRARY_PATH=/opt/rti.com/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0
++ clean /home/rosteam/uros_ws/install/micro_ros_setup
+++ sed 's/ /:/g'
++++ echo /home/rosteam/uros_ws/install/micro_ros_setup
++++ sed 's/:/\n/g'
+++++ echo /home/rosteam/uros_ws/install:/opt/ros/crystal
+++++ sed 's/:/\|/g'
++++ grep -v -E '(/home/rosteam/uros_ws/install|/opt/ros/crystal)'
+++ echo
++ echo
+ export CMAKE_PREFIX_PATH=
+ CMAKE_PREFIX_PATH=
/home/rosteam/uros_ws/install/micro_ros_setup/lib/micro_ros_setup/build_firmware.sh: line 40: PYTHON_PREFIX_PATH: unbound variable
+ export PYTHON_PREFIX_PATH=
+ PYTHON_PREFIX_PATH=
++ clean /opt/rti.com/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0:/opt/rti.com/rti_connext_dds-5.3.1/bin:/opt/ros/crystal/bin:/home/rosteam/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
+++ sed 's/ /:/g'
++++ echo /opt/rti.com/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0:/opt/rti.com/rti_connext_dds-5.3.1/bin:/opt/ros/crystal/bin:/home/rosteam/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
++++ sed 's/:/\n/g'
+++++ sed 's/:/\|/g'
+++++ echo /home/rosteam/uros_ws/install:/opt/ros/crystal
++++ grep -v -E '(/home/rosteam/uros_ws/install|/opt/ros/crystal)'
+++ echo /opt/rti.com/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0 /opt/rti.com/rti_connext_dds-5.3.1/bin /home/rosteam/.local/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin
++ echo /opt/rti.com/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0:/opt/rti.com/rti_connext_dds-5.3.1/bin:/home/rosteam/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
+ export PATH=/opt/rti.com/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0:/opt/rti.com/rti_connext_dds-5.3.1/bin:/home/rosteam/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
+ PATH=/opt/rti.com/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0:/opt/rti.com/rti_connext_dds-5.3.1/bin:/home/rosteam/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
+ unset AMENT_PREFIX_PATH
+ unset COLCON_PREFIX_PATH
+ pushd firmware/dev_ws
+ colcon build
Starting >>> ament_package

Summary: 52 packages finished [26.9s]
+ set +o nounset
+ . install/setup.bash
++++ dirname install/setup.bash
+++ builtin cd install
+++ pwd
++ COLCON_CURRENT_PREFIX=/home/rosteam/uros_ws/firmware/dev_ws/install
++ _colcon_prefix_chain_bash_source_script /home/rosteam/uros_ws/firmware/dev_ws/install/local_setup.bash
++ '[' -f /home/rosteam/uros_ws/firmware/dev_ws/install/local_setup.bash ']'
++ '[' -n '' ']'
++ . /home/rosteam/uros_ws/firmware/dev_ws/install/local_setup.bash
+++ '[' -z /home/rosteam/uros_ws/firmware/dev_ws/install ']'
+++ _colcon_prefix_bash_COLCON_CURRENT_PREFIX=/home/rosteam/uros_ws/firmware/dev_ws/install
+++ _colcon_prefix_bash_prepend_unique_value COLCON_PREFIX_PATH /home/rosteam/uros_ws/firmware/dev_ws/install
+++ _listname=COLCON_PREFIX_PATH
+++ _value=/home/rosteam/uros_ws/firmware/dev_ws/install
+++ eval '_values="$COLCON_PREFIX_PATH"'
++++ _values=
+++ _colcon_prefix_bash_prepend_unique_value_IFS=' 	
'
+++ IFS=:
+++ _all_values=/home/rosteam/uros_ws/firmware/dev_ws/install
+++ unset _item
+++ IFS=' 	
'
+++ unset _colcon_prefix_bash_prepend_unique_value_IFS
+++ eval export 'COLCON_PREFIX_PATH="/home/rosteam/uros_ws/firmware/dev_ws/install"'
++++ export COLCON_PREFIX_PATH=/home/rosteam/uros_ws/firmware/dev_ws/install
++++ COLCON_PREFIX_PATH=/home/rosteam/uros_ws/firmware/dev_ws/install
+++ unset _all_values
+++ unset _values
+++ unset _value
+++ unset _listname
+++ unset _colcon_prefix_bash_prepend_unique_value
+++ '[' -n '' ']'
+++ _colcon_python_executable=/usr/bin/python3
+++ '[' '!' -f /usr/bin/python3 ']'
++++ /usr/bin/python3 /home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py sh bash
Traceback (most recent call last):
  File "/home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py", line 295, in <module>
    main()
  File "/home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py", line 49, in main
    args.additional_extension
  File "/home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py", line 179, in get_commands
    package_dsv_path, prefix, primary_extension, additional_extension)
  File "/home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py", line 224, in process_dsv_file
    additional_extension=additional_extension)
  File "/home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py", line 199, in process_dsv_file
    type_, remainder, prefix)
  File "/home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py", line 262, in handle_dsv_types_except_source
    commands += _prepend_unique_value(env_name, value)
  File "/home/rosteam/uros_ws/firmware/dev_ws/install/_local_setup_util_sh.py", line 278, in _prepend_unique_value
    if not env_state[name]:
KeyError: 'CMAKE_PREFIX_PATH'
+++ _colcon_ordered_commands='export PATH="/home/rosteam/uros_ws/firmware/dev_ws/install/ament_clang_format/bin:$PATH"
export PYTHONPATH="/home/rosteam/uros_ws/firmware/dev_ws/install/ament_clang_format/lib/python3.6/site-packages:$PYTHONPATH"
export AMENT_PREFIX_PATH="/home/rosteam/uros_ws/firmware/dev_ws/install/ament_clang_format"
export PATH="/home/rosteam/uros_ws/firmware/dev_ws/install/ament_copyright/bin:$PATH"
export PYTHONPATH="/home/rosteam/uros_ws/firmware/dev_ws/install/ament_copyright/lib/python3.6/site-packages:$PYTHONPATH"
export AMENT_PREFIX_PATH="/home/rosteam/uros_ws/firmware/dev_ws/install/ament_copyright:$AMENT_PREFIX_PATH"
export PATH="/home/rosteam/uros_ws/firmware/dev_ws/install/ament_cppcheck/bin:$PATH"
export PYTHONPATH="/home/rosteam/uros_ws/firmware/dev_ws/install/ament_cppcheck/lib/python3.6/site-packages:$PYTHONPATH"
export AMENT_PREFIX_PATH="/home/rosteam/uros_ws/firmware/dev_ws/install/ament_cppcheck:$AMENT_PREFIX_PATH"
export PATH="/home/rosteam/uros_ws/firmware/dev_ws/install/ament_cpplint/bin:$PATH"
export PYTHONPATH="/home/rosteam/uros_ws/firmware/dev_ws/install/ament_cpplint/lib/python3.6/site-packages:$PYTHONPATH"
export AMENT_PREFIX_PATH="/home/rosteam/uros_ws/firmware/dev_ws/install/ament_cpplint:$AMENT_PREFIX_PATH"
export PATH="/home/rosteam/uros_ws/firmware/dev_ws/install/ament_flake8/bin:$PATH"
export PYTHONPATH="/home/rosteam/uros_ws/firmware/dev_ws/install/ament_flake8/lib/python3.6/site-packages:$PYTHONPATH"
export AMENT_PREFIX_PATH="/home/rosteam/uros_ws/firmware/dev_ws/install/ament_flake8:$AMENT_PREFIX_PATH"'

**Comment by iluetkeb** [comment]
Hmm, the last error log looks as if you got some change in the build_firmware.sh file wrong.

Anyway, I managed to replicate the error using the latest ROS 2 Crystal packages. Apparently something changed in the meantime that doesn't react well to empty environment variables, but I had not updated before, so I didn't notice it.

I have now created a branch https://github.com/micro-ROS/micro-ros-build/tree/fix/unset-variables that should address this issue. Using that branch, the problem goes away on my box. Have a try!

**Comment by Viplav04** [comment]
Thank you. I am able to flash the board. Although there are some stderr CMake warnings in compiling the typesupport packages. I think the USB configurations are set to something different which I will have to change manually to launch the nsh client.
