### ISSUE TITLE
apt update breaks firmware create script

### ISSUE THREAD

**Issue by eden-desta** [micro-ROS/micro_ros_setup#169]
The apt update placed on line 74 breaks the script if you are running the create firmware step. 
Upon removing it, the system worked. 

This should likely be removed because a user will manually run the update prior to running the script anyways.

**Comment by pablogs9** [comment]
Hello @eden-desta, can you try if this changes https://github.com/micro-ROS/micro_ros_setup/pull/172 fixes this issue?

I guess that you had troubles with `apt update` permissions right?

**Comment by eden-desta** [comment]
@pablogs9 you should not have to run it with sudo. If you remove that, the build works.

**Comment by pablogs9** [comment]
Yes, but have to be sure that apt is up-to-date. Do you propose any solution for automating this in the creation script?
