### ISSUE TITLE
ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyUSB0 Inside Docker

### ISSUE THREAD

**Issue by thihakyawjob** [micro-ROS/micro_ros_setup#174]
Dear,
The following command does not work inside docker system.
**ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyUSB0**

How can I access ttyUSB0 from docker image?

Please guide me.

![AgentError](https://user-images.githubusercontent.com/12581592/89726753-b957cf80-da50-11ea-89c7-e475073c4eb8.png)

Regards,
Thiha Kyaw

**Comment by DorBenHarush** [comment]
Hi,
You need to share the dev directory with the docker container in the creation like this:
docker run -it --net=host -v /dev:/dev --privileged  ros:foxy
Then type in the container:
ls /dev/serial/by-id/*
to find the name of the device, use it for --dev.

Regards,
Dor Ben Harush.

**Comment by pablogs9** [comment]
Thanks @DorBenHarush for the contribution.

This should resolve the Docker issues.
