### ISSUE TITLE
Debugging a NuttX Application Tutorial for microros

### ISSUE THREAD

**Issue by thihakyawjob** [micro-ROS/micro_ros_setup#177]
Dear ROS Team,
I try to follow Debugging a NuttX Application Tutorial. I didn't understand the tutorial. Therefore I want to ask some questions.

I already download "git clone --depth 1 https://github.com/sony/openocd-nuttx".

But I cannot find **.gdbinit:** file. Please guide me. 

Do I need to download a separate Nuttx? In tutorial, "On Nuttx 7.27, the result should look something like this:". I don't understand this part also.

I use Ubuntu 20.04 and I didn't use docker. But I still cannot find **.gdbinit:**.

Please explain more detailed about tutorial.

Debugging is necessary when we want to use a customized board.

Thank ROS team.

Regards,
Thiha Kyaw

**Comment by JanStaschulat** [comment]
Hi @thihakyawjob, 
thank you for your request. The colleagues from Eprosima are on holiday until 21.08. They will come back on this question as soon as possible.
