### ISSUE TITLE
Add new board in microROS

### ISSUE THREAD

**Issue by MARLARCHAN** [micro-ROS/micro_ros_setup#188]
I'm currently trying to add new board in microROS used for waveshared Core4X9I (STM32F429IGTb).

1. Could you provide me which Nuttx version is used for microROS. 

2. According to Nuttx Porting guide, there is board folder under this directory nuttx/nuttx/boards.
But in microROS, i cannot find boards folder under firmware/Nuttx/

Please suggest me for my issues.

Best Regards,
Marlar

**Comment by pablogs9** [comment]
Hello @MARLARCHAN 

1. As you know, the Nuttx port of micro-ROS is a fork of the original repo. If you check the ChangeLog you can find that the last entry points to `7.29 2019-03-25` version.
2. you can find the available configurations here: `firmware/NuttX/configs`

Hope this answers your questions.
