### ISSUE TITLE
Debugging Nuttx Application

### ISSUE THREAD

**Issue by MARLARCHAN** [micro-ROS/micro_ros_setup#200]
![Nuttx_Debug_gdbCommandIssue](https://user-images.githubusercontent.com/46348612/94781678-bd72ee80-03fc-11eb-8acb-f3cbd87b419f.png)
Dear MicroROS Team,
I'm trying to add customize message for new application. so Debugging for Nuttx is needed.

So, I'm trying firstly Debugging NuttX Application Tutorial with Ubuntu 20.04  But, I don't understand the tutorial. 
After downloading  "git clone --depth 1 https://github.com/sony/openocd-nuttx", I cannot find .gdbinit: file. Do I need to create by myself? 

Also although i installed arm-none-eabi-gdb, I cannot do this command:  "arm-none-eabi-gdb nuttx"

I can only use with this command "gdb nuttx", and it shows the error as follow:
arm-none-eabi-gdb nuttx
(gdb) print-offset

Best Regards.
Marlar

**Comment by pablogs9** [comment]
Hello @MARLARCHAN, I'm not the maintainer of this tutorial but I have been reading it and maybe you should create this `.gdbinit` in the directory with the content detailed in the tutorial:

```
define print-offset
 printf "#define PID  %p\n",&((struct tcb_s *)(0))->pid
 printf "#define XCPREG  %p\n",&((struct tcb_s *)(0))->xcp.regs
 printf "#define STATE %p\n",&((struct tcb_s *)(0))->task_state
 printf "#define NAME %p\n",&((struct tcb_s *)(0))->name
 printf "#define NAME_SIZE %d\n",sizeof(((struct tcb_s *)(0))->name)
end
```

---

@ralph-lange @FranFin What should we do with these Nuttx tutorials? Is there any maintainer for them?

**Comment by MARLARCHAN** [comment]
Dear @pablogs9 ,

    I have created .gdbinit file. After that, I can only use the command " gdb nuttx " instead of " arm-none-eabi-gdb nuttx".  And the error is still as in above attachment. Please advise me something.


Thank you 
Best Regards,
Marlar

**Comment by MARLARCHAN** [comment]
Dear @ralph-lange @FranFin @pablogs9 
           Please suggest me this issue also! Thank you.


Best Regards,
Marlar
