### ISSUE TITLE
Unable to locate ros-foxy-google-benchmark-vendor

### ISSUE THREAD

**Issue by CLansdaleBEC** [micro-ROS/micro_ros_setup#204]
Hello, this issue just popped up when trying to run create_firmware_ws.sh. It doesn't look like it's board/rtos specific. 

I'm using Ubuntu 20.04 with Foxy, and ran an apt update before testing

![Screenshot from 2020-10-06 12-14-11](https://user-images.githubusercontent.com/66074066/95228681-a43bba80-07cd-11eb-979c-85ac3193c86f.png)

**Comment by vibnwis** [comment]
Having see your message, I took a close look of mine, me too experienced the same error.

**Comment by vibnwis** [comment]
out of curiosity, what is that for? the ros-foxy-google-benchmark-vendor

**Comment by pablogs9** [comment]
They have updated `ament_cmake` adding this new dependency but it seems not to be resolving well `ros-foxy-google-benchmark-vendor`. Check this: https://github.com/ament/ament_cmake/commits/foxy

I have opened an issue in this package: https://github.com/ament/ament_cmake/issues/285

I'm working on a fix here: https://github.com/micro-ROS/micro_ros_setup/pull/205, I will alert you when merged (this morning).

**Comment by pablogs9** [comment]
Hello @CLansdaleBEC and @vibnwis, https://github.com/micro-ROS/micro_ros_setup/pull/205 merged, this problem should be fixed.

Thanks a lot for reporting!
