### ISSUE TITLE
MicroROS Agent for new custom message 

### ISSUE THREAD

**Issue by MARLARCHAN** [micro-ROS/micro_ros_setup#207]
Dear @pablogs9 

      I'm trying to test with new custom message. 
     I attach the app.c file in here. 
     I can debug and compile firmware. 
    According to your link, I use std_msg. But when I test agent running, nsh is aborting. 
    Please guide me how can I solve.

Best Regards,
Marlar
![NSH uros_packet_test Aborting](https://user-images.githubusercontent.com/46348612/95438936-8dda5e00-0989-11eb-85f9-7be508342f0c.png)

[app.txt](https://github.com/micro-ROS/micro_ros_setup/files/5346583/app.txt)

**Comment by pablogs9** [comment]
You are creating two nodes using the same `rcl_node_t` struct.

Check lines 53 and 54:

```c
RCCHECK(rclc_node_init_default(&node, "int32_publisher", "", &support));
RCCHECK(rclc_node_init_default(&node, "int32_subscriber", "", &support));
```

I recommend you using the same node for creating the subscriber and the publisher, just:

```c
RCCHECK(rclc_node_init_default(&node, "my_microros_node", "", &support));
```

**Comment by pablogs9** [comment]
Close if solved, please.

**Comment by MARLARCHAN** [comment]
Thank you. I can solve right now.
