### ISSUE TITLE
Micro-ROS in Nucleo-h743zi

### ISSUE THREAD

**Issue by arunlee77** [micro-ROS/micro_ros_setup#214]
Hi,
Is there any wiki/document available on how to enable microros on nucleo-h734zi with nuttx?

regards
Arun

**Comment by pablogs9** [comment]
Hello @arunlee77 there is no official support for Nucleo h734zi and Nuttx, please check the [official list of supported boards](https://github.com/micro-ROS/micro_ros_setup#supported-platforms) and if you achieve a working port for this platform PR are welcome.

**Comment by IshanBhatnagar14** [comment]
it is supported on Zephyr RTOS.
