### ISSUE TITLE
Build agent errors

### ISSUE THREAD

**Issue by RajasJ99** [micro-ROS/micro_ros_setup#227]
when ran command in workspace: ros2 run micro_ros_setup create_agent_ws.sh , got the following error:
![rosdep](https://user-images.githubusercontent.com/33423968/99085061-c1924e80-25ed-11eb-99f7-0d3ce48bab8e.png)

Also when tried build the agent found another error : 
![agent](https://user-images.githubusercontent.com/33423968/99085197-e981b200-25ed-11eb-9cd2-8b782a3f744f.png)
 
The two errors are probably not related because the first one is due to :rosdep install and the later is due to micr_ros_agent directory

**Comment by FilipStarkenberg** [comment]
I have the exact same error. Tested on two machines running Ubuntu 20.04.

**Comment by pablogs9** [comment]
Did you install the prerequisites? 

`sudo apt install python3-rosdep`

![image](https://user-images.githubusercontent.com/7647884/99091405-2179fc80-25d0-11eb-9042-cdc7e15a1b2d.png)

**Comment by FilipStarkenberg** [comment]
Yes I did and I have a fresh installation of foxy. I think there is some sort of problem with fastrtps.

**Comment by RajasJ99** [comment]
The first error has gone now , forgot to install python3-rosdep ,but the second error remains, tried completely rebuilding my workspace but the error is still there

**Comment by pablogs9** [comment]
Hello everyone. Sorry for this error.

I have reset the `foxy` branch to in Micro XRCE-Agent  to a34ad20a6dcc457cf34a3df97cacb87b00a2ff9d, so it should be working again.

I'm closing since solved, please reopen if any other issue.

CC: @jamoralp
