### ISSUE TITLE
Harmonize programmer selection in flash step

### ISSUE THREAD

**Issue by RobertWilbrandt** [micro-ROS/micro_ros_setup#233]
Currently, every platform has its own logic to select which openocd programmer to use. It might make sense to merge this together, as it is not really platform dependent (actually only depending on usb devices connected). This would also help in cases like #230, as you can just fix this quickly for all cases (btw: shouldn't you be able to program every st nucleo/discovery board with some st-link device?).

I am willing to create a PR for this soon.

**Comment by pablogs9** [comment]
Hello @RobertWilbrandt, I also think that flashing scripts can be highly improved but we have had not time to polish them.

If you propose some PR it would be awesome! Thanks a lot.
