### ISSUE TITLE
MicroROS Build Error

### ISSUE THREAD

**Issue by MARLARCHAN** [micro-ROS/micro_ros_setup#235]
Dear @pablogs9 ,

   I found an issue when I have to rebuild microROS from start again. I use foxy with ubuntu20.04 without using docker. I followed all the steps and use with stm32f429-disco. The issue happen when I choose micro-ROS Ping Pong in menu config. The issue is the following:
I tried with usbnsh and with drivebase which I copy drivebase to stm32f429-disco, but issue is still happen. 
Please suggest me the issue related with.

![image](https://user-images.githubusercontent.com/46348612/99929859-bd062c80-2d89-11eb-99d3-f02c45555f59.png)

**Comment by pablogs9** [comment]
I guess that you are using Nuttx, is this right? I'm sorry but right now micro-ROS for stm32f429-disco is only supported for Zephyr. Have you tried to test the Zephyr port?
