### ISSUE TITLE
Zephyr / micro-ros Boad names differ

### ISSUE THREAD

**Issue by NielsKorschinsky** [micro-ROS/micro_ros_setup#239]
Hello,

I'm just opening this here so it can be recognized.
I'm using the Discovery L475 IOT1 boad. It has two different board names, depending whether I am using zephyr or micro-ros directly. This should probably be unified.

| Zephyr | Micro-ROS|
| ----- | ----- |
| disco_l475_iot1 | discovery_l475_iot1 |

Thanks!

**Comment by pablogs9** [comment]
This renaming respond to a old solution and we have not fixed it yet. You can check it [here](https://github.com/micro-ROS/micro_ros_setup/blob/2051643258e915f972fc78070e9fb43c1264f550/config/zephyr/generic/build.sh#L51).

I'm sure that if you use `ros2 run micro_ros_setup zephyr disco_l475_iot1` it will work in the same way. Let me know if this works for you.

I'll keep this open to remind us to modify this. If you want to contribute with a PR for this would be super nice.
