### ISSUE TITLE
Starting a project on MicroROS 

### ISSUE THREAD

**Issue by Vishnu-Vijay95** [micro-ROS/micro_ros_setup#260]
Hi All,
 I am going to start a project on micro Ros on freeRTOS on olimex STM32E407 board and i am using segger jlink for programing.
I want to know what are the steps i need to follow while starting a new project on microROS.

**Comment by pablogs9** [comment]
Hello @Vishnu-Vijay95, have you tried the steps in our [Olimex STM32E407 + FreeRTOS tutorial](https://micro-ros.github.io/docs/tutorials/core/first_application_rtos/freertos/)?

If so, could you detail which problems have you find following these steps?

**Comment by pablogs9** [comment]
PD: maybe to get in touch with the micro-ROS build system you can test the [micro-ROS for Linux tutorial](https://micro-ros.github.io/docs/tutorials/core/first_application_linux/)

**Comment by Vishnu-Vijay95** [comment]
Hai @pablogs9 , I tried to flashing the microROS firmware using the flashing script **ros2 run micro_ros_setup flash_firmware.sh** but this script is only for OpenOCD programmer. But i don't have this hardware and i am using segger jlink for programing. I have successfully flashed micro-ROS binary using an alternative method. Next have done the micro_ROS agent and stared the agent using command **ros2 run micro_ros_agent micro_ros_agent serial --dev [device]**. For the connection from USART to USB i have used a USB to TTL convertor, but i am getting an error **open device error  errno:2**.

**Comment by Vishnu-Vijay95** [comment]
Hai @pablogs9 , I tried flashing the microROS firmware using the flashing script **ros2 run micro_ros_setup flash_firmware.sh** but this script is only for OpenOCD programmer, i don't have this hardware and i am using segger jlink for programing. I have successfully flashed micro-ROS binary using an alternative method. Next have done the micro_ROS agent and stared the agent using command **ros2 run micro_ros_agent micro_ros_agent serial --dev [device].** For the connection from USART to USB i have used a USB to TTL convertor, but i am getting an error **open device error errno:2**.

**Comment by pablogs9** [comment]
Could you please share the whole command for `ros2 run micro_ros_agent micro_ros_agent serial --dev [device]` and the output of `ls /dev/serial/by-id/`?

**Comment by Vishnu-Vijay95** [comment]
Thanks @pablogs9 for your support . i had rectified the problem. I was not giving the entire device name was just giving the device ID. Now tried to subscribe the ping topic and getting the warning : **topic [/microROS/ping] does not appear to be published yet**. whether it is due to incorrect flashing?

**Comment by pablogs9** [comment]
Can you paste here the output of your agent? Remember to add the flag `-v6` for verbosity.

**Comment by Vishnu-Vijay95** [comment]
This the output of the agent :
**command : ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyUSB0
[1611298569.543361] info     | TermiosAgentLinux.cpp | init                     | running...             | fd: 3**

**Comment by pablogs9** [comment]
please use the flag `-v6` in the agent command

**Comment by Vishnu-Vijay95** [comment]
**command: ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyUSB0 -v6
[1611302815.849160] info     | TermiosAgentLinux.cpp | init                     | running...             | fd: 3
[1611302815.849394] info     | Root.cpp           | set_verbose_level        | logger setup           | verbose_level: 6**
logger setup is active now.

**Comment by pablogs9** [comment]
can you share the ouput of `ls /dev/serial/by-id/`?

**Comment by Vishnu-Vijay95** [comment]
**ls /dev/serial/by-id/ : usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0**

**Comment by pablogs9** [comment]
Can you try `ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0 -v6`?

**Comment by Vishnu-Vijay95** [comment]
command : `ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0 -v6`
[1611304478.932185] info     | TermiosAgentLinux.cpp | init                     | running...             | fd: 3
[1611304478.932419] info     | Root.cpp           | set_verbose_level        | logger setup           | verbose_level: 6

command : `source /opt/ros/foxy/setup.bash`
command : `ros2 topic echo /microROS/ping`
WARNING: topic [/microROS/ping] does not appear to be published yet
Could not determine the type for the passed topic

**Comment by pablogs9** [comment]
Can you show how have you connected the UART-USB cable to the board?

**Comment by Vishnu-Vijay95** [comment]
yes. How can i share ?

**Comment by pablogs9** [comment]
Documentation of your cable model and a photo of the conection to the board.

**Comment by Vishnu-Vijay95** [comment]
For Connection i am using normal jumper cables.
Board connection, i am attaching here 
https://drive.google.com/file/d/1QapEIOaiNv0R2j23nJ7xyIljGz06Jq--/view?usp=sharing
https://drive.google.com/file/d/1JAs_UaKSWFtlOuhJmRkZ71rjoyPc4j-x/view?usp=sharing

**Comment by pablogs9** [comment]
Have you checked the correctness of Tx and Rx?

**Comment by Vishnu-Vijay95** [comment]
Yes i checked by looping the Tx and Rx i am getting the output. I don't know  whether its any flashing error. I had flashed micro-ROS.bin file to the MCU. I had used segger JLink for programming so the firmware flashing script didn't work for me as its written for OpenOCD programmer.

**Comment by pablogs9** [comment]
Try to use the on board USB following the tutorial but using the following configuration command:

```bash
ros2 run micro_ros_setup configure_firmware.sh ping_pong --transport serial-usb
```

**Comment by Vishnu-Vijay95** [comment]
Hi @pablogs9 i tried this configuration command and getting the following output
```
Configuring firmware for freertos platform olimex-stm32-e407
Using serial USB device. EXPERIMENTAL.
cp: cannot stat '/home/ignitarium/Desktop/mros_ws/firmware/freertos_apps/microros_olimex_e407_extensions/Src/olimex_e407_usb_transport.c': No such file or directory
cp: cannot stat '/home/ignitarium/Desktop/mros_ws/firmware/freertos_apps/microros_olimex_e407_extensions/Inc/olimex_e407_usb_transport.h': No such file or directory
Configured serial-usb mode with agent
```
Shows some header files are missing. Can you help me in flashing the board using  segger JLink

**Comment by pablogs9** [comment]
Sorry I didn't remember that we had this USB transport as experimental. Try to use [this branch](https://github.com/micro-ROS/freertos_apps/tree/feature/usb_olimex) for the repo in firmware/freertos_apps.

**Comment by pablogs9** [comment]
I just have replicated the tutorial using an Olimex STM32-E407 board and serial communication and everything works as expected. Do you have any way of checking if your board is generating the UART? Maybe using another USB-UART cable? Checking with an oscilloscope?

**Comment by Vishnu-Vijay95** [comment]
Ok @pablogs9, How you flashed the the olimex Board? You used [ARM-USB-TINY-H ](https://www.olimex.com/Products/ARM/JTAG/ARM-USB-TINY-H/)for programing. I don't have this hardware.

**Comment by pablogs9** [comment]
Sorry, I can't test with another programmer because I only have this one.

**Comment by Vishnu-Vijay95** [comment]
Ok @pablogs9, How you flashed the the olimex Board? You used [ARM-USB-TINY-H ](https://www.olimex.com/Products/ARM/JTAG/ARM-USB-TINY-H/)for programing? I don't have this hardware.

**Comment by Vishnu-Vijay95** [comment]
I am getting some packages stderr while building, do you encounter same issue.
```
Summary: 59 packages finished [3min 12s]
  37 packages had stderr output: action_msgs actionlib_msgs builtin_interfaces composition_interfaces diagnostic_msgs example_interfaces geometry_msgs libyaml_vendor lifecycle_msgs micro_ros_msgs microxrcedds_client nav_msgs rcl rcl_action rcl_interfaces rcl_lifecycle rcl_logging_noop rclc rclc_lifecycle rcutils rmw rmw_implementation rmw_microxrcedds rosgraph_msgs rosidl_runtime_c rosidl_typesupport_c rosidl_typesupport_microxrcedds_c sensor_msgs shape_msgs statistics_msgs std_msgs std_srvs stereo_msgs test_msgs trajectory_msgs unique_identifier_msgs visualization_msgs

```
but the build was complete with stderr.

**Comment by pablogs9** [comment]
Yes, this is not a problem. All packages have been built but due to cross-compilation, there are some warnings.

**Comment by Vishnu-Vijay95** [comment]
Ok Thanks @pablogs9,  i will try some alternative to flash.

**Comment by Vishnu-Vijay95** [comment]
The freeRTOS + microROS ping_pong is available with the RTOS? or we have to port this package into freeRTOS? Why i asked because if i have to do a custom project on microROS + freeRTOS, whether i am able to use the same build system or i have to port microROS application to freeRTOS entirely?

**Comment by pablogs9** [comment]
Not entirely but the parts that use the FreeRTOS API in your user code.

**Comment by Vishnu-Vijay95** [comment]
In the ping_pong pgm i had listed all ros2 topics the output was
```
ros2 topic list
/parameter_events
/rosout
```
the topic micoROS/ping is not available. what will be the possible problem.

**Comment by pablogs9** [comment]
Your micro-ROS client is not creating entities in the micro-ROS agent, please double-check the serial transport and if possible try with another serial-to-USB cable.

**Comment by Vishnu-Vijay95** [comment]
I tested USB-serial communication on Zephyr its working fine for me. I tried USB-serial communication in freeRTOS with the repo provided by you i am getting an error while building I will state it below.
```

home/ignitarium/Desktop/microros_ws/firmware/mcu_ws/eProsima/Micro-XRCE-DDS-Client/src/c/profile/transport/serial/serial_transport_external.c:24: undefined reference to `CDC_DeInit_FS'
collect2: error: ld returned 1 exit status
make: *** [Makefile:386: /home/ignitarium/Desktop/microros_ws/firmware/freertos_apps/microros_olimex_e407_extensions/build/micro-ROS.elf] Error 1
```

the build is  failing with the ERROR code 1

**Comment by pablogs9** [comment]
It is ok for you to use Zephyr?

**Comment by Vishnu-Vijay95** [comment]
Actually looking forward to use freeRTOS. Can u help me?

**Comment by Vishnu-Vijay95** [comment]
Thanks @pablogs9, i rectified it. It was my UART  problem. Thanks for your support.

**Comment by pablogs9** [comment]
Nice, I'm closing this issue.

Please, don't hesitate to reopen if you have any question.

**Comment by Vishnu-Vijay95** [comment]
Hi @pablogs9 ,  I going to start a custom app in microROS +freeRTOS. where are the changes i have to make to register <my_app>

**Comment by pablogs9** [comment]
just create your app in `firmware/freertos_apps/apps/` and execute the `ros2 run micro_ros_setup` and you should see your new folder

**Comment by Vishnu-Vijay95** [comment]
Is this command complete? i just created `my_app` folder and saved `app.c `and `app-colon.meta` file in `firmware/freertos_apps/apps/`

**Comment by pablogs9** [comment]
Paste here the output of `ros2 run micro_ros_setup`

**Comment by Vishnu-Vijay95** [comment]
this it the output
```
usage: ros2 run [-h] [--prefix PREFIX] package_name executable_name ...
ros2 run: error: the following arguments are required: executable_name, argv
```

**Comment by pablogs9** [comment]
oh sorry: `ros2 run micro_ros_setup configure_firmware.sh`

**Comment by Vishnu-Vijay95** [comment]
Ya now its showing my_apps. Now it it does not require any additional configuration, right? But while building i am getting an error:
```
/home/microros_ws/firmware/toolchain/bin/../lib/gcc/arm-none-eabi/8.3.1/../../../../arm-none-eabi/bin/ld: /home/Desktop/microros_ws/firmware/freertos_apps/microros_olimex_e407_extensions/build/micro-ROS.elf section `.bss' will not fit in region `RAM'
/home/Desktop/microros_ws/firmware/toolchain/bin/../lib/gcc/arm-none-eabi/8.3.1/../../../../arm-none-eabi/bin/ld: region `RAM' overflowed by 76472 bytes
collect2: error: ld returned 1 exit status
make: *** [Makefile:372: /home/Desktop/microros_ws/firmware/freertos_apps/microros_olimex_e407_extensions/build/micro-ROS.elf] Error 1
```
But i have written the same ping_pong code in my app.

**Comment by pablogs9** [comment]
paste here your `app-colcon.meta`

**Comment by Vishnu-Vijay95** [comment]
```
 "names": {
        "rmw_microxrcedds": {
            "cmake-args": [
                "-DRMW_UXRCE_MAX_NODES=1",
                "-DRMW_UXRCE_MAX_PUBLISHERS=2",
                "-DRMW_UXRCE_MAX_SUBSCRIPTIONS=3",
                "-DRMW_UXRCE_MAX_SERVICES=0",
                "-DRMW_UXRCE_MAX_CLIENTS=0",
                "-DRMW_UXRCE_MAX_HISTORY=4",
            ]
        }
    }
}
```

**Comment by pablogs9** [comment]
Try to build it in a clean environment. The ping_pong app should fit the Olimex STM32-E407 RAM, please try it in a clean environment, and if it still does not fit (super strange because the ping_pong app works), you can decrease the entities, for example, `DRMW_UXRCE_MAX_HISTORY`.

You can find more information about middleware optimization [here](https://micro-ros.github.io/docs/tutorials/core/microxrcedds_rmw_configuration/).

**Comment by Vishnu-Vijay95** [comment]
I am able to build the `ping_pong `app successfully, i have copied and pasted the same code on `my_app` then its showing RAM overflow error. Are u sure that there is no additional settings needed to be done to register the my_apps folder means, any cmake list edit is required?

**Comment by pablogs9** [comment]
As far as I know, you only need to create a new folder in the apps folder. You have copied literally the same code?

**Comment by Vishnu-Vijay95** [comment]
Earlier i had made some changes as well, since it was not building i literally copied the same code and tried again. But the build was failing

**Comment by pablogs9** [comment]
I guess that you are doing some changes. I have replicated here the procedure of copying the ping-pong app as we are talking and everything builds fine:

https://asciinema.org/a/Lh0hPfRIMOJhYRvEvA9DmGYSd

**Comment by Vishnu-Vijay95** [comment]
Ok, let me check

**Comment by Vishnu-Vijay95** [comment]
> I guess that you are doing some changes. I have replicated here the procedure of copying the ping-pong app as we are talking and everything builds fine:
> 
> https://asciinema.org/a/Lh0hPfRIMOJhYRvEvA9DmGYSd
Ok Thanks. Rectified

**Comment by Vishnu-Vijay95** [comment]
I have an logical doubt. If i need to interface an sensor to mcu and thereby publish the sensor data, where i have to write my subscriber? whether its ros2 subscriber? if yes, what are the steps to interface microROS and ros2? i think my question is logically correct

**Comment by pablogs9** [comment]
You will have a sensor connected to an MCU, this MCU will run micro-ROS and you need to create a publisher that send the sensor data.

This micro-ROS code needs to connect to the micro-ROS Agent, and once it is connected, you will be able to see the data being published in ROS 2 with the normal commands such as:

`ros2 topic echo ...`

**Comment by Vishnu-Vijay95** [comment]
Hi @pablogs9, I am trying to write a microROS+ freertos program to control a kobuki turtle bot 2 robot. I had taken your [code ](https://github.com/pablogs9/kobuki_esp32_micro_ros/blob/96a65c9156edbc560c81849c45aecb680518b7e0/main/kobuki_microros.c#L102)  as reference. I am doing this on an olimex STM32E407 board. But while building i am getting an error `drive_base_msgs/msg/base_info.h: No such file or directory` . Thing this header file is missing.

**Comment by pablogs9** [comment]
That's because [drive_base](https://github.com/micro-ROS/drive_base) is a custom message. If you have a common micro-ROS environment, just:

```bash
git clone https://github.com/micro-ROS/drive_base firmware/mcu_ws/uros/drive_base
ros2 run micro_ros_setup build_firmware.sh
```

And you should be able to use it.

**Comment by Vishnu-Vijay95** [comment]
Thanks, now `kobuki.h` is also having same error. Header file missing.

**Comment by pablogs9** [comment]
Do you have a solution for that? Is solved by just including the header?

Could you do a PR if solved? Or share your project if you need support.

**Comment by Vishnu-Vijay95** [comment]
I am really new to robotics side programing, i am proficient only in RTOS side. That is  why i am reaching out for support. I am doing a project on RTOS side performance analysis of microROS.

**Comment by Vishnu-Vijay95** [comment]
Hi @pablogs9, I am going to do freeRTOS app to control the kobuki robot. I tried the reconstruct ur [code](https://github.com/pablogs9/kobuki_esp32_micro_ros/blob/96a65c9156edbc560c81849c45aecb680518b7e0/main/kobuki_microros.c#L102). i got some header file issues. if i need to develop a custom app, where i have to keep the required header files for building. Its in mcu_ws folder or dev_ws folder or i can keep in in the app folder itself

**Comment by pablogs9** [comment]
If you are using the micro-ros-setup scripts for Olimex board you can check how your application is build checking the [Makefile](https://github.com/micro-ROS/freertos_apps/blob/foxy/microros_olimex_e407_extensions/Makefile).

As you can see [all the .c files in you app folder](https://github.com/micro-ROS/freertos_apps/blob/74cd38c0a283e66741881d62b5f0967640927179/microros_olimex_e407_extensions/Makefile#L164) are being build and [your app folder will be added as include search path](https://github.com/micro-ROS/freertos_apps/blob/74cd38c0a283e66741881d62b5f0967640927179/microros_olimex_e407_extensions/Makefile#L253).

**Comment by Vishnu-Vijay95** [comment]
You are referring to makefile in the path /firmware/freertos_apps/microros_olimex_e407_extensions, right?

**Comment by pablogs9** [comment]
The one in the link

**Comment by Vishnu-Vijay95** [comment]
@pablogs9 can you please provide your email or hangout id.

**Comment by Vishnu-Vijay95** [comment]
`TaskHandle_t` is of which type? where it is defined?

**Comment by Vishnu-Vijay95** [comment]
in this microROs kubuki [code](https://github.com/pablogs9/kobuki_esp32_micro_ros/blob/96a65c9156edbc560c81849c45aecb680518b7e0/main/kobuki_microros.c#L102) `TaskHandle_t `is of which type? where its is defined?

**Comment by pablogs9** [comment]
https://www.freertos.org/a00019.html#xTaskHandle

**Comment by Vishnu-Vijay95** [comment]
```
/firmware/freertos_apps/apps/Kobuki_run/app.c:129:2: error: unknown type name 'TaskHandle_t'
  TaskHandle_t kobuki_handle = NULL;
```
freertos/task.h is included

**Comment by pablogs9** [comment]
This is not a micro-ROS problem. Please check your FreeRTOS linkage and includes.

**Comment by Vishnu-Vijay95** [comment]
`RCCHECK(rmw_uros_options_set_udp_address(CONFIG_MICRO_ROS_AGENT_IP, CONFIG_MICRO_ROS_AGENT_PORT, rmw_options));`
what does this represent in you [code](https://github.com/pablogs9/kobuki_esp32_micro_ros/blob/96a65c9156edbc560c81849c45aecb680518b7e0/main/kobuki_microros.c#L102) 
Where `CONFIG_MICRO_ROS_AGENT_IP, CONFIG_MICRO_ROS_AGENT_PORT` are declared

**Comment by Vishnu-Vijay95** [comment]
> This is not a micro-ROS problem. Please check your FreeRTOS linkage and includes.

Ok i will check. Thanks

**Comment by pablogs9** [comment]
This code is for ESP32 IDF toolchain, these are configuration variables of this toolchain. 

You can check the [micro-ROS RMW API](https://github.com/micro-ROS/rmw-microxrcedds/blob/68adec19d27ad7d1ede92d475d59f040b4c05b6c/rmw_microxrcedds_c/include/rmw_uros/options.h#L93) to know how to use these functions. In any case, if you are using a serial transport you won't need agent IP and port.

**Comment by Vishnu-Vijay95** [comment]
Ok Thanks, in this you are not using any URDF robot description file. Without this file how you can initialize the robot? Plz correct me if i am wrong.

**Comment by Vishnu-Vijay95** [comment]
Hi @pablogs, Have you tried the kobuki tutorial provided in the [microROS page.](https://micro.ros.org/docs/tutorials/demos/kobuki_demo/)

**Comment by Vishnu-Vijay95** [comment]
Hi @pablogs9 , have you tried the microROS kobuki demo provided in [microROS page](https://micro.ros.org/docs/tutorials/demos/kobuki_demo/). I cant find the microROS port of thin_kobuki driver.

**Comment by pablogs9** [comment]
@ralph-lange do you know anything about this Kobuki demo provided in https://github.com/micro-ROS/micro-ROS_kobuki_demo?

**Comment by Vishnu-Vijay95** [comment]
Hi @ralph-lange the repo is now active? i raised an same issue in it as well. can u please help me in this aspect ?

**Comment by ralph-lange** [comment]
Hi @Vishnu-Vijay95, the Kobuki demo hasn't been ported to Foxy yet (which should be straightforward). The latest branch is https://github.com/micro-ROS/nuttx_apps/tree/demo/safe_kobuki. Please note that the current implementation requires for the Olimex board and NuttX requires a separate device for WiFi. You may consider to use an ESP32 with integrated WiFi, which is supported by micro-ROS since summer 2020.

**Comment by ralph-lange** [comment]
Postscript: We would be happy to add your port for FreeRTOS to the https://github.com/micro-ROS/freertos_apps/ repo and adapt the description in https://github.com/micro-ROS/micro-ROS_kobuki_demo/ and on the micro-ROS website accordingly.
We are constantly on the lookout for developers from the community who would like to take over care of a demo or package.

**Comment by Vishnu-Vijay95** [comment]
Thanks @ralph-lange, i was really searching for a lead in this issue. Thanks for replying. i found the safe_kobuki demo earlier as well, but i didn't found a method for building the app. I have no option to change the development board. so i have to stick with the olimex board.  Actually i am doing a project on RTOS side performance analysis of microROS and my aim is to compare the RTOS which best suits for an application. So in order to find the multitasking performance i am planing have 2 tasks one for controlling the robot and other to read an sensor data. This is an overview of my project.

**Comment by ralph-lange** [comment]
When staying with the Olimex board, the easiest setup on the Kobuki is to connect a tiny USB powered access point (with a USB power bank) via Ethernet.

**Comment by ralph-lange** [comment]
You're welcome! You may also reach us on micro-ros.slack.com. Furthermore, you're invited to present your topic in one of the next Embedded WG meetings.

**Comment by Vishnu-Vijay95** [comment]
Hi @pablogs9 , i am using the microROS build system for the project. Can you guide me over in accessing hardware peripherals from microROS node written inside app.c. I am able to access the peripherals  from main.c file in the Olimex extension folder . I would like to toggle an led or send a custom data over UART from microROS nodes from app.c. 
Eager for your reply :))

**Comment by pablogs9** [comment]
Hey @Vishnu-Vijay95 micro-ROS build system for your platform uses a common STM32CubeMX project, so you should be able to use the common HAL interface of CMSIS API as you do in a CubeMX project for accessing any of your board's peripherals.

**Comment by Vishnu-Vijay95** [comment]
Thanks @pablogs9 I figured it out.

**Comment by Vishnu-Vijay95** [comment]
@pablogs9 do you encounter this error anytime. I had written a custom publisher pgm to interface a sensor but i am getting an error in the debug terminal. Its showing RCL init has failed and showing microROS app in block state.
![Screenshot from 2021-03-23 16-58-29](https://user-images.githubusercontent.com/70762767/112140065-89cd9000-8bf9-11eb-87fa-fd48da517efd.png) i cheched it with an pgm from tutorial, i am getting the same error there as well.

**Comment by pablogs9** [comment]
I need more details for answering:
1. using micro_ros_setup or IDF?
2. your application code
3. transport that are you using
4. how are you using the micro-ROS agent

In general, provide instructions for replication of your error.
This error means that your client is not reaching the micro-ROS Agent.

**Comment by Vishnu-Vijay95** [comment]
Can i setup this with out providing transport, just i want check a printed value on debug terminal UART6. Now its getting terminated on execution.

**Comment by Vishnu-Vijay95** [comment]
Hi @pablogs9, while writing the turtle bot driver how you have calculated the CRC value. I just collected the responce data from the kobuki base and i got byte stream like this 
``AA 55 4D 01 0F 7C 15 00 03 01 00 00 00 00 00 00 00 00 A1 00 03 03 00 00 00 04 07 6F FD A4 FF 00 00 00 05 06 4C 02 68 02 83 02 06 02 00 00 0D 0E 4D 06 36 00 BE FF 9D FF 2B 00 B9 FF 99 FF 10 10 00 00 FF 0F FF 0F FF 0F FF 0F F0 0F 00 00 00 00 48 AA`
here whether 48 is the crc value? i need to know the crc calculation algorithm for this. can you help me this aspect

**Comment by ralph-lange** [comment]
For the demo we ported the [thin_kobuki driver](https://github.com/Lab-RoCoCo/thin_drivers/tree/master/thin_kobuki).
You can find parseBuffer function in the port for NuttX at https://github.com/micro-ROS/nuttx_apps/blob/kobuki_rcl_port/examples/kobuki/kobuki_protocol.cxx#L447.

**Comment by ralph-lange** [comment]
You may want to have a look at the checkSum function of the driver in the [kobuki_core](https://github.com/kobuki-base/kobuki_core) repository: https://github.com/kobuki-base/kobuki_core/blob/devel/src/driver/kobuki.cpp#L39

**Comment by Vishnu-Vijay95** [comment]
Hi @pablogs9 and @ralph-lange, i made a custom driver for kobuki and the control program and wireless teleop is working fine for me with microROS. I prefer to add one more task to microROS along with robot control. i Prefer to interface a RP lidar with my olimex board. Is it possible, have checked such a scenario? if not can you show me another task which i can implement easily with microROS.

**Comment by ralph-lange** [comment]
Hi @Vishnu-Vijay95, we have discussed interfacing a LiDAR several times in the past, but have never tackled this. In my opinion, this is a very interesting scenario for micro-ROS at it would allow to implement a low-level, quickly reacting behavior for obstacle avoidance. Given the fact that micro-ROS does not support an efficient inter-node communication on the MCU (but only via the agent), you should put the functions in one node for the time being.
