### ISSUE TITLE
Build error: DT_N_INST_0_DT_DRV_COMPAT_IRQ_NAME_USB_IRQ_NAME_VAL_irq using zephyr on nucleo_h743zi

### ISSUE THREAD

**Issue by nasher128** [micro-ROS/micro_ros_setup#272]
## Build Issue

- Hardware description: nucleo_h743zi
- RTOS: zephyr
- Installation type: ros2 run micro_ros_setup build_firmware.sh
- Version or commit hash: Latest as of 9/2/2021

#### Steps to reproduce the issue
Following the setup tutorial here: https://micro-ros.github.io//docs/tutorials/core/first_application_rtos/zephyr/
1) I setup my workspace and specify my development board nucleo_h743zi, using  
2) I run "ros2 run micro_ros_setup configure_firmware.sh ping_pong --transport serial-usb"
3) Then "ros2 run micro_ros_setup build_firmware.sh" and the build fails

#### Expected behavior

Building the firmware for my nucleo_h743zi

#### Actual behavior

In file included from /home/nash/Work/microros_ws/firmware/zephyrproject/zephyr/include/arch/arm/aarch32/irq.h:19,
                 from /home/nash/Work/microros_ws/firmware/zephyrproject/zephyr/include/arch/arm/aarch32/arch.h:27,
                 from /home/nash/Work/microros_ws/firmware/zephyrproject/zephyr/include/arch/cpu.h:19,
                 from /home/nash/Work/microros_ws/firmware/zephyrproject/zephyr/include/kernel_includes.h:33,
                 from /home/nash/Work/microros_ws/firmware/zephyrproject/zephyr/include/kernel.h:17,
                 from /home/nash/Work/microros_ws/firmware/zephyrproject/zephyr/include/init.h:11,
                 from /home/nash/Work/microros_ws/firmware/zephyrproject/zephyr/include/device.h:22,
                 from /home/nash/Work/microros_ws/firmware/zephyrproject/zephyr/include/drivers/usb/usb_dc.h:20,
                 from /home/nash/Work/microros_ws/firmware/zephyrproject/zephyr/include/usb/usb_device.h:39,
                 from /home/nash/Work/microros_ws/firmware/zephyrproject/zephyr/drivers/usb/device/usb_dc_stm32.c:53:
/home/nash/Work/microros_ws/firmware/zephyrproject/zephyr/drivers/usb/device/usb_dc_stm32.c: In function 'usb_dc_ep_write':
/home/nash/Work/microros_ws/firmware/zephyrproject/zephyr/include/devicetree.h:300:40: error: 'DT_N_INST_0_DT_DRV_COMPAT_IRQ_NAME_USB_IRQ_NAME_VAL_irq' undeclared (first use in this function)
  300 | #define DT_INST(inst, compat) UTIL_CAT(DT_N_INST, DT_DASH(inst, compat))

**Comment by pablogs9** [comment]
Hello, as you can see in the [micro_ros_setup readme](https://github.com/micro-ROS/micro_ros_setup#configuring-micro-ros-firmware) nucleo_h743zi is a community-contributed board that only has support for UART.

I'm closing due to the lack of official support, if you make any upgrade for using this board with USB serial transport, PR are **really** welcome.

Thanks!
