### ISSUE TITLE
microROS agent- client serial communication is not working in zephyr RTOS

### ISSUE THREAD

**Issue by Vishnu-Vijay95** [micro-ROS/micro_ros_setup#305]
RTOS: Zephyr
MCU : olimex STM32E407

Tried the microROS zephyr RTOS int32_publisher program on olimex STM32E407 board. Tried agent client communication through usb-serial and its working fine. Tired the same with serial communication but the agent client communication is not establishing.
![Screenshot from 2021-04-19 19-19-58](https://user-images.githubusercontent.com/70762767/115247306-4d337c80-a144-11eb-9f30-32d3987731b8.png)

**Comment by pablogs9** [comment]
Have you configured the serial port that you want to use [here](https://github.com/micro-ROS/zephyr_apps/blob/89e85c8cf29647d276203735a49a41ecbc4b8dd1/microros_extensions/microros_transports.h#L47)?

**Comment by Vishnu-Vijay95** [comment]
Ok thanks @pablogs9
