### ISSUE TITLE
Micro-ros agent create_participant DDS error

### ISSUE THREAD

**Issue by colomonoir** [micro-ROS/micro_ros_setup#314]
## Issue template

- Hardware description: STM32
- RTOS: freeRTOS
- Installation type: micro_ros_setup
- Version: foxy

#### Steps to reproduce the issue
I was following this guide on https://micro.ros.org/docs/tutorials/core/first_application_rtos/freertos/
I connected the olimex and my pc to a switch via ethernet cables and an ethernet to USB converter
I ran theses commands:
`ros2 run micro_ros_setup configure_firmware.sh int32_publisher -t udp -i 192.168.1.35 -p 8888`
`ros2 run micro_ros_setup build_firmware.sh `
`ros2 run micro_ros_setup flash_firmware.sh `
`docker run -it --rm --net=host -v /dev/shm:/dev/shm --privileged microros/micro-ros-agent:foxy udp4 --port 8888 -v6`

#### Expected behavior
No DDS error

#### Actual behavior
![image](https://user-images.githubusercontent.com/83817457/117442900-a7e81900-af37-11eb-8870-c3ca229f5d7e.png)

**Comment by gavanderhoorn** [comment]
Apologies for bumping an old thread, but I just ran into this problem myself, and it took me quite some time to figure out the Agent was not compatible with the version of the Client running on the device.

Would there be some way for the Agent to print a more informative error message, or something on the client side?

The client reported something like "Issues running micro XRCE-DDS session", which is rather generic as well.

**Comment by pablogs9** [comment]
Yes, probably your client is using the binary entity creation mode and the agent is an old version that only supports XML and references.

I'll check how to include an error message that alerts about this.
Thanks.
