### ISSUE TITLE
Unable to establish udp connection with microROS client in zephyr RTOS

### ISSUE THREAD

**Issue by Vishnu-Vijay95** [micro-ROS/micro_ros_setup#336]
## Issue template

- Hardware description:  Olimex STM32E407
- RTOS: Zephyr
- Installation type: microROS setup
- Version or commit hash: version of micro-ROS used: foxy

#### Steps to reproduce the issue
```
ros2 run micro_ros_setup create_firmware_ws.sh zephyr olimex-stm32-e407
ros2 run micro_ros_setup configure_firmware.sh int32_publisher -t udp -i 192.168.0.105 -p 8888
```
### Output
![Screenshot from 2021-06-08 12-56-08](https://user-images.githubusercontent.com/70762767/121141894-14b54280-c859-11eb-9b5a-70ec6381a1ca.png)

**Comment by Acuadros95** [comment]
`micro_ros_setup` is looking for the Zephyr configuration inside the example folder, but right now we don't provide that file for the udp transport. 

You can try to create your own and place it inside the int32_publisher folder with the expected name: `udp.conf` or `proj.conf` (default conf file). 

The following configuration could serve as a starting point:

```
# micro-ROS options
CONFIG_MAIN_STACK_SIZE=25000
CONFIG_MAIN_THREAD_PRIORITY=3

CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_NANO=n
CONFIG_CPLUSPLUS=y
CONFIG_LIB_CPLUSPLUS=y
CONFIG_PTHREAD_IPC=n

CONFIG_POSIX_API=y
CONFIG_NATIVE_POSIX_TIMER=y
CONFIG_APP_LINK_WITH_POSIX_SUBSYS=y
CONFIG_POSIX_CLOCK=y

# Network options
CONFIG_NET_IPV4=y
CONFIG_NET_CONFIG_NEED_IPV4=y
CONFIG_NET_DHCPV4=y
CONFIG_LOG=y
CONFIG_NET_UDP=y
CONFIG_NETWORKING=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_POSIX_NAMES=y
```
