### ISSUE TITLE
install/micro_ros_setup/lib/micro_ros_setup/yaml_filter.py

### ISSUE THREAD

**Issue by AIxWALL** [micro-ROS/micro_ros_setup#364]
Hello! I am trying to run an example on the Zephyr Emulator by following the micro-ROS application tutorial for RTOS and getting some errors while building.

## Operating System:

- Ubuntu 20.04.2 LTS

#### Steps to reproduce the issue

$ros2 run micro_ros_setup create_firmware_ws.sh zephyr host
...
Skip distro "ardent" different from requested "foxy"
Skip distro "bouncy" different from requested "foxy"
Skip distro "crystal" different from requested "foxy"
Skip distro "dashing" different from requested "foxy"
Skip distro "eloquent" different from requested "foxy"
Add distro "foxy"
Skip distro "galactic" different from requested "foxy"
Skip distro "groovy" different from requested "foxy"
Skip distro "hydro" different from requested "foxy"
Skip distro "indigo" different from requested "foxy"
Skip distro "jade" different from requested "foxy"
Skip distro "kinetic" different from requested "foxy"
Skip distro "lunar" different from requested "foxy"
Skip distro "melodic" different from requested "foxy"
Skip distro "noetic" different from requested "foxy"
Skip distro "rolling" different from requested "foxy"
updated cache in /home/harmony/.ros/rosdep/sources.cache
#All required rosdeps installed successfully
Traceback (most recent call last):
  File "/home/harmony/workspace/microros_ws_zephyr/install/micro_ros_setup/lib/micro_ros_setup/yaml_filter.py", line 15, in <module>
    for key in repos_info["repositories"]:
TypeError: 'NoneType' object is not subscriptable

is there any package i am missing? or any other steps to follow? 
Thank you very much.

**Comment by pablogs9** [comment]
Which release of micro-ROS are you targeting? Galactic or Foxy?

**Comment by AIxWALL** [comment]
foxy.I've tried many times and it's the same error

**Comment by pablogs9** [comment]
Check this patch: https://github.com/micro-ROS/micro_ros_setup/pull/365

**Comment by AIxWALL** [comment]
thanks.the error message disappears. it should download some packages from github,e.g. ament/ament_cmake,but it didn`t,i wonder why. 
also
when Configuring the firmware with the following command:
$ros2 run micro_ros_setup configure_firmware.sh ping_pong --transport udp --ip 127.0.0.1 --port 8888
the following error appears:
~/workspace/microros_ws_zephyr/firmware/zephyr_apps/apps: No such file or directory

**Comment by pablogs9** [comment]
Which version of Python are you using?

**Comment by AIxWALL** [comment]
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux

**Comment by pablogs9** [comment]
I have had no problems replicating this: https://asciinema.org/a/v5U7tsx80e52owitp90kafZ9K

**Comment by AIxWALL** [comment]
i appreciate it, and i will check

**Comment by Acuadros95** [comment]
Closing, feel free to reopen on any update.
