### ISSUE TITLE
micro_ros_setup No definition of [python3-vcstool] for OS [osx]

### ISSUE THREAD

**Issue by srliu** [micro-ROS/micro_ros_setup#371]
I'm tying to install a micro-ROS development on my Macbook (Big Sur11.4) and have run into issues after the following steps:

> /# Update dependencies using rosdep
> sudo rosdep update
> rosdep install --from-path src --ignore-src -y

I end up with the error:
> ERROR: the following packages/stacks could not have their rosdep keys resolved to system dependencies:
> micro_ros_setup: No definition of [python3-vcstool] for OS [osx]

Looking at file `ros/rosdistro/rosdep/python.yaml `, it appears there is indeed no key for `osx`:

> python3-vcstool:
>     alpine: [vcstool]
>  debian:
>   pip:
>     packages: [vcstool]
>  fedora: [python3-vcstool]
>   gentoo:
>    pip:
>      packages: [vcstool]
>   macports:
>    pip:
>     packages: [vcstool]
>  ubuntu: [python3-vcstool]

My python version is Python 3.9.2. ROS2 version is Foxy.

Can anyone help with this issue?

**Comment by pablogs9** [comment]
micro-ROS build system is not available in macOS.
