### ISSUE TITLE
command line explanation - micro-ROS Tutorials

### ISSUE THREAD

**Issue by Jabed-Akhtar** [micro-ROS/micro_ros_setup#375]
## Issue template

- Hardware description: 
- RTOS: 
- Installation type: 
- Version or commit hash: 

#### Question
Can someone please explain me this command line
'ros2 run micro_ros_setup create_firmware_ws.sh nuttx olimex-stm32-e407'

* where will I get expalantions about the command lines? Documentation?
* From above command line, I want to use esp32 or stm32f4 Board instead of olimex-stm32-e407, how to do that in working way?

**Comment by pablogs9** [comment]
Hello @Jabed-Akhtar, I guess that you'll usefull information reading the first steps tutorials: https://micro.ros.org/docs/tutorials/core/overview/
