### ISSUE TITLE
Creating a minimal, git-friendly project

### ISSUE THREAD

**Issue by asasine** [micro-ROS/micro_ros_setup#379]
Do you have any suggestions for creating and managing a micro-ROS project in git?

My goals are to:
1. keep the project dependencies small (I noticed the [Linux host tutorial](https://micro.ros.org/docs/tutorials/core/first_application_linux/) created 40+ packages by cloning 17 repos into the src directory)
1. reliably reproduce behavior when cloned to another machine (e.g., using submodules to reliably retrieve dependencies with a specific version instead of cloning directly into the src directory)

I apologize if this documentation already exists; I wasn't able to find anything.

---
## System info
Hardware: Raspberry Pi 4 Model B
OS: Ubuntu 20.04
Installation type: micro_ros_setup
micro-ROS agent type: Linux host
Version: galactic

**Comment by pablogs9** [comment]
Hello, usually micro-ROS tends to use the same ROS 2 approach for managing dependencies and packages. Thus, there is no project with the structure you propose. 

Please if you make it keep us updated.
