### ISSUE TITLE
Unable to compile micro ROS agent on arm processor

### ISSUE THREAD

**Issue by wegunterjr** [micro-ROS/micro_ros_setup#424]
## Issue template

- Hardware description: raspberry pi 3/4
- raspbian 
- Installation type: <micro_ros_setup
- Version or commit hash:  foxy, galactic

#### Steps to reproduce the issue
Tried cloning repo and running colon build

#### Expected behavior
Micro ROS bridge folder created 
#### Actual behavior
Fails on finding libraries...

**Comment by pablogs9** [comment]
micro-ROS bridge is a deprecated concept in micro-ROS. Are you meaning micro-ROS Agent? 
Please provide detailed instructions to replicate your issue.

**Comment by pablogs9** [comment]
Please provide detailed instructions to replicate your issue.

**Comment by wegunterjr** [comment]
Ah... Grabbing my computer to recreate,  but quick summary is that thr docker for thr agent is multi-arch so won't run on an arm processor like an Xavier Agx.

**Comment by pablogs9** [comment]
You are mixing versions... if you are using ROS 2 Foxy make sure that the `micro_ros_setup` repo in checkout to `foxy`. If you are using ROS 2 Galactic, use `galactic` branch.

This error is because there are ABI breaks between Foxy and Galactic.

**Comment by wegunterjr** [comment]
i will make sure again by confirming I am using the galactic branch. 
I pulled the osrf/ros2 galactic docker image, and cloned micro_ros_setup.

**Comment by wegunterjr** [comment]
`updated cache in /root/.ros/rosdep/sources.cache
executing command [apt-get install -y flex]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package flex is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'flex' has no installation candidate
ERROR: the following rosdeps failed to install
  apt: command [apt-get install -y flex] failed`

**Comment by wegunterjr** [comment]
alright... successful.   I was able to build it in a galactic docker on an arm processor.  That's nice!
