### ISSUE TITLE
dpkg doesn't exist on Fedora

### ISSUE THREAD

**Issue by eaglesemanation** [micro-ROS/micro_ros_setup#436]
- Hardware description: esp32
- RTOS: FreeRTOS
- Installation type: micro_ros_setup
- Version or commit hash: galactic

#### Steps to reproduce the issue
Try to create workspace

#### Expected behavior
Successful creation of firmware folder

#### Actual behavior
Fails to check if pip3 is installed in [`config/freertos/esp32/create.sh`](https://github.com/micro-ROS/micro_ros_setup/blob/33bd36a3338db24ea2c46d755380eb92cea0d267/config/freertos/esp32/create.sh#L17)

#### Additional information
Probably the easiest fix to that would be to replace `dpkg -s python3-pip > /dev/null` with `which pip3 >/dev/null 2>&1`

**Comment by pablogs9** [comment]
Hello @eaglesemanation,

Fedora is not a Tier 1 platform in ROS 2, so we do not have support for this OS at micro-ROS. We will be happy to review a PR where you make some patches for solving that.

Thanks for the feedback.
