### ISSUE TITLE
rcutils wrongly builds atomic_64

### ISSUE THREAD

**Issue by bjv-capra** [micro-ROS/micro_ros_setup#505]
In recent builds, I've detected that I had to change my rcutils flag from `-DRCUTILS_NO_64_ATOMIC=ON` to `-DRCUTILS_NO_64_ATOMIC=OFF` in order to actually build without it.

Using nm -C I could see the object present. This seems to have been introduced in https://github.com/micro-ROS/rcutils/commit/500ee3fcb16bf6260453c75b50c3d7785d724443#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a

**Comment by pablogs9** [comment]
Is it enough to explain it better like here: https://github.com/micro-ROS/rcutils/pull/17 ?

**Comment by bjv-capra** [comment]
I think it'd do. It was just quite of a breaking change :). Thanks!
