### ISSUE TITLE
micro-ros release for humble

### ISSUE THREAD

**Issue by JanStaschulat** [micro-ROS/micro_ros_setup#514]
see error report on ros discourse:

https://discourse.ros.org/t/branched-humble-call-for-beta-testing/25284/15

**Comment by pablogs9** [comment]
micro-ROS Humble is not ready yet. We will work in this discussion: https://github.com/micro-ROS/micro_ros_setup/discussions/509

**Comment by pablogs9** [comment]
micro-ROS Humble released
