### ISSUE TITLE
USB support for STM32-E407 with FreeRTOS

### ISSUE THREAD

**Issue by roni-kreinin** [micro-ROS/micro_ros_setup#520]
Are there any plans to support `serial-usb` for the STM32-E407 running FreeRTOS?

**Comment by pablogs9** [comment]
Hello @roni-kreinin, there are no plans to support this transport. In any case, I recommend you use [micro-ROS for STM32CubeMX/IDE](https://github.com/micro-ROS/micro_ros_stm32cubemx_utils) if you are working with E407. serial-usb is neither implemented there, but we can provide some support if you have plans for integrating it.
