### ISSUE TITLE
Callback not firing for joint_state 

### ISSUE THREAD

**Issue by eecue** [micro-ROS/micro_ros_setup#534]
## Issue template

- Hardware description: Arduino/OpenCR
- RTOS: n/a
- Installation type: Build and flash 
- Version or commit hash: galactic

#### Steps to reproduce the issue
When I send a Twist message this works fine:

https://github.com/eecue/6dof_arm_eecue_opencr_ros/blob/bc6a995a9c094df90e8657e1f2cf465ed3b4828c/6dof_arm_eecue_opencr_ros.ino

`ros2 topic pub -1 /eecue_6dof_arm_subscriber geometry_msgs/msg/Twist '{linear: {x: 100.0,y: 10.0, z: 20.0}, angular: {x: 90.0, y: 100.0, z: 80.0}}'` 

However when I send joint_state the callback doesn't fire (I've added some random positions there to see if it ever gets called and it doesn't.  Here's the code for the joint_state message:

https://github.com/eecue/6dof_arm_eecue_opencr_ros/blob/main/6dof_arm_eecue_opencr_ros.ino 

Here's how I'm calling it: `ros2 topic pub -1 /eecue_6dof_arm_subscriber sensor_msgs/msg/JointState "{name: ['shoulder','forearm','elbow','arm_rotate','wrist_flex','wrist_rotate'], position: [1,1,1,1,1,1], velocity: [1.0,1,1,1,1,1], effort: [1.0,1,1,1,1,1]}"`

Any idea what I'm doing wrong here?

**Comment by pablogs9** [comment]
`sensor_msgs__msg__JointState * msg;` is a not initialized pointer.

Please check your code, you need to have an instance of the type `sensor_msgs__msg__JointState` and then apply the rules for micro-ROS memory allocations: https://micro.ros.org/docs/tutorials/advanced/handling_type_memory/ç

For example:

```
sensor_msgs__msg__JointState msg;

void setup() {
...

  // Init header frame id string
  msg.header.frame_id.capacity = STRING_SIZE;
  msg.header.frame_id.size = 0;
  msg.header.frame_id.data = (char*) malloc(STRING_SIZE * sizeof(char));

...
}
```
