### ISSUE TITLE
Messages not being published or agent not running

### ISSUE THREAD

**Issue by MiguelMartinez-HAW** [micro-ROS/micro_ros_setup#544]
Hello everyone!

I am trying to get started with Micro-ROS, so I got one of the officially supported boards, the Espressif ESP32-WROOM-32E.

### Steps that led to the problem 
I followed [this tutorial](https://micro.ros.org//docs/tutorials/core/first_application_rtos/freertos/), except they use the Olimex STM32-E407 evaluation board, so to create the firmware I used this line
`ros2 run micro_ros_setup create_firmware_ws.sh freertos esp32`
as they did [here](https://medium.com/@SameerT009/connect-esp32-to-ros2-foxy-5f06e0cc64df). I don't really need wireless communication, serial is fine for my application; so except for that line, I followed everything else according to that first tutorial.

Everything went well up to the part where you run the micro-ROS agent.
```
# Run a micro-ROS agent
ros2 run micro_ros_agent micro_ros_agent serial --dev [device]
```
I use this command to find my serial device name: `ls /dev/serial/by-id/*`
What I get is: `/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_b20cb0bd8019ec11ad010fb5f01c6278-if00-port0`

## The problem
So I run the micro-ROS agent with the device name I got above. This is how it looks:
![image](https://user-images.githubusercontent.com/85174880/179505637-8c2ed135-d43b-428c-9776-1604d0265539.png)
Then, I try to echo the topic in another window and as you can see in the image below, the topic is not published.
![image](https://user-images.githubusercontent.com/85174880/179506122-4821df2c-e645-457f-8f50-3122983341e6.png)

### Expected behavior
While the messages stop for me after _init_ and _set_vebose_level_, other tutorials show more steps, such as _topic created_, _publisher created_, etc. Here's a picture taken from the second tutorial I mentioned; although they use wifi there, so I'm not sure what to expect in my case, but probably something similar.
![image](https://user-images.githubusercontent.com/85174880/179507184-e9a147b6-0e34-4dda-b651-637a3893abaa.png)
While echoing the topic, I would expect to see this:
![image](https://user-images.githubusercontent.com/85174880/179508369-57504218-a192-48e2-9c24-995dcee2afba.png)

## Solutions I already tried but didn't solve the problem

First, trying to visualize the output with the flag -v6 didn't do much other than changing the verbose level shown.
![image](https://user-images.githubusercontent.com/85174880/179516083-dd80016b-459a-40da-b9fb-c378d45e33cc.png)

 Using ROS_DOMAIN_ID=30 also didn't change anything
![image](https://user-images.githubusercontent.com/85174880/179509030-63d7efe0-c85f-45ce-a4d6-fdc28c623281.png)
![image](https://user-images.githubusercontent.com/85174880/179516289-af30bbf9-7a8c-4478-8c04-71ae756991e3.png)

I also followed [this advice](https://github.com/micro-ROS/micro_ros_arduino/issues/223#issuecomment-830682880) and unplugged the cable on both ends and within 2 seconds I ran:
`ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_b20cb0bd8019ec11ad010fb5f01c6278-if00-port0 -b 115200 -v6`
But still, nothing changed nor it showed anything on rqt.

[Here](https://github.com/micro-ROS/micro_ros_setup/issues/179#issuecomment-823168096) they also suggested pressing the reset button but that didn't work either.

Finally, I tried using the dockerized version of the micro-ROS Agent, as recommended [here](https://github.com/micro-ROS/micro_ros_arduino/issues/7#issuecomment-717964787). Unfortunately, I still had the same problem. Images below.
![image](https://user-images.githubusercontent.com/85174880/179513531-3b5fddea-ebfd-497f-9c50-654db6b7fbff.png)
![image](https://user-images.githubusercontent.com/85174880/179513592-c6bc44aa-672d-4d94-a3e2-27f11fd955fe.png)

As you can see, I've been trying to solve this issue for quite some time. If you have any more ideas or can detect something wrong with my approach, I'd appreciate your input.

Perhaps you guys have an idea about what's wrong? @Kakcalu13 @pablogs9 @nfry321 @MARLARCHAN

### System information
- OS: Ubuntu 20.04.4
- ROS 2 Foxy
- ESP32-WROOM-32E

**Comment by pablogs9** [comment]
Please move to the ESP-IDF module for micro-ROS in order to develop ESP32 applications with micro-ROS: https://github.com/micro-ROS/micro_ros_espidf_component.

Please report if you find any problem using the module with ESP 32 serial transport.

**Comment by MiguelMartinez-HAW** [comment]
Hello!

Sorry for the late update. I had to focus on other parts of the robot for a while. 
I started over the tutorials mentioned above and this time they worked fine. I didn't have any problems anymore. Perhaps it was a matter of flashing the firmware again.

Then I moved to the ESP-IDF module as @pablogs9 suggested. (I am a newbie with ESP-IDF so [this tutorial](https://youtu.be/dOVjb2wXI84) helped me get started). I then configured the WiFi settings and after executing `idf.py monitor` it threw an error. These are the last lines printed on the terminal:
```
I (1592) wifi_station_netif: got ip:1XX.1XX.1XX.XX
I (1592) wifi_station_netif: connected to ap SSID:****** password:******
Failed status on line 54: 1. Aborting.
```
I actually want to communicate through UART instead of WiFi, so I moved on and went to change the transport method by `idf.py menuconfig` and in `micro-ROS Settings->micro-ROS network interface select` I changed it to `Micro XRCE_DD over UART` 
When building though, it fails. These are the last lines printed on terminal:
```
-- Configuring done
-- Generating done
-- Build files have been written to: /home/miguel/esp/esp-idf/components/micro_ros_espidf_component/examples/int32_publisher/build/bootloader
[1/1] cd /home/miguel/esp/esp-idf/components/micro_ros_espidf_component/examples/int32_publisher/build/bootloader/esp-idf/esptool_py && /home/miguel/.espressif/python_env/idf4.4_py3.8_env/bin/python /home/miguel/esp/esp-idf/components/partition_table/check_sizes.py --offset 0x8000 bootloader 0x1000 /home/miguel/esp/esp-idf/components/micro_ros_espidf_component/examples/int32_publisher/build/bootloader/bootloader.bin
Bootloader binary size 0x62c0 bytes. 0xd40 bytes (12%) free.
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
```
Do I have to modify the code or create some definitions somewhere to use serial transport?
In the menu, when I selected `Micro XRCE_DD over UART`, it also said: `Check int32_publisher_custom_transport`.  I'm not sure how to proceed. 
Any tips regarding this problem?

**Comment by MiguelMartinez-HAW** [comment]
I've been battling with this error for a while. At this point, I'm wondering, if this method works https://micro.ros.org//docs/tutorials/core/first_application_rtos/freertos/ what's the advantage of using this module https://github.com/micro-ROS/micro_ros_espidf_component ?

**Comment by Acuadros95** [comment]
> UPDATE: I realized this code is for Humble. I switched to Foxy and got this [error](https://github.com/micro-ROS/micro_ros_espidf_component#dependencies). I'm looking into it.

The link is not leading to any error. As your error on `Humble` looks related to a missconfiguration on micro-ROS selected transport on our side, we will look into it.

> what's the advantage of using this module.

`micro_ros_setup` is going to be deprecated in favor of vendor specific build systems.

**Comment by MiguelMartinez-HAW** [comment]
Thank you very much for your reply. I'm sorry for the wrong link, I corrected it. In that [link](https://github.com/micro-ROS/micro_ros_espidf_component/issues/53) I also posted the errors I had when trying to solve it. While the error is solved for `foxy`, I'll use `micro_ros_setup` in the meantime. Is it possible to do multitasking with `micro_ros_setup`?
