### ISSUE TITLE
Build time is too long using build_firmware.sh

### ISSUE THREAD

**Issue by vecna-ad** [micro-ROS/micro_ros_setup#545]
We are using MicroROS and Zephyr on a custom STM32-based board.  When running the build_firmware.sh script (`ros2 run micro_ros_setup build_firmware.sh`) it takes a very long time to build the firmware (minutes). It's only marginally faster when using the -f flag.  Building is very slow even if no source files are modified.  We can see that many object files are rebuilt each time.  This seems wrong.  Any ideas on how to make building faster?  This slows rapid code development.

When building zephyr only using `west build`, everything compiles very quickly and no un-touched source files are recompiled.

**Comment by pablogs9** [comment]
Just use the micro-ROS module for Zephyr and customize your build procedure: https://github.com/micro-ROS/micro_ros_zephyr_module

It is true that the micro_ros_setup scripts will rebuild the whole environment in order to handle changes in the micro-ROS installation.
