### ISSUE TITLE
MicroRos agent installation failed

### ISSUE THREAD

**Issue by DhevanVasu** [micro-ROS/micro_ros_setup#547]
Hi,
I am trying to install microros agent in my ubuntu 20.04 machine and ros2 foxy version is installed.
While installing am getting below error.

```
vasu@vasu:~/Micro_Ros/agentws$ ros2 run micro_ros_setup build_agent.sh
Building micro-ROS Agent
Starting >>> micro_ros_msgs
--- stderr: micro_ros_msgs                             
make[1]: *** No rule to make target 'micro_ros_msgs__py/CMakeFiles/micro_ros_msgs__py.dir/all', needed by 'CMakeFiles/micro_ros_msgs__python.dir/all'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:146: all] Error 2
---
Failed   <<< micro_ros_msgs [1.36s, exited with code 2]
```

Summary: 0 packages finished [1.55s]
  1 package failed: micro_ros_msgs
  1 package had stderr output: micro_ros_msgs
  1 package not processed

Please help me to resolve this issue.

**Comment by pablogs9** [comment]
Make sure that you run `rosdep update && rosdep install --from-paths src --ignore-src -y` to install `micro_ros_msgs` dependency. It should be done automatically by the build process.

If this does not work just clone [`micro_ros_msgs` repo](https://github.com/micro-ROS/micro_ros_msgs) in your src folder before building the agent.
