### ISSUE TITLE
Logic broken in check if generic platform

### ISSUE THREAD

**Issue by k7g03z** [micro-ROS/micro_ros_setup#550]
https://github.com/micro-ROS/micro_ros_setup/blob/7e07042c256cc34a4e972f6e36f1724fc7a5c38d/scripts/build_firmware.sh#L72

I believe the proper check is:

`if [ $PLATFORM == "generic" ] && [ -d "$PREFIX/config/$RTOS/generic" ]; then`

**Comment by pablogs9** [comment]
Please open a PR with the fix

**Comment by Kay-Anonymous** [comment]
actually， `creat_firmware.sh ` are as same as build_firmware.sh for the generic check .......

**Comment by k7g03z** [comment]
@Kay-Anonymous I am preparing a MR that fixes `create_firmware.sh` as well. Had to clarify open-source contribution permission company-internally first...

**Comment by Acuadros95** [comment]
Closing as PR was merged
