### ISSUE TITLE
How to call the /get_parameter service on micro-ROS

### ISSUE THREAD

**Issue by Jenifen** [micro-ROS/micro_ros_setup#585]
- Hardware description: Machinecontrol h7
- Version : foxy

**Question**: How to get ROS parameter hosted by another Node in micro ros ? 

Thanks,

**Comment by pablogs9** [comment]
micro-ROS only has a parameter server and does not have a parameter client.

This way, you need to use:
 - ROS 2 CLI
 - ROS 2 rclcpp or rclpy
 - Manage to call directly to the underlying service, you have an example of a service client here: https://github.com/micro-ROS/micro-ROS-demos/blob/humble/rclc/addtwoints_client/main.c
