### ISSUE TITLE
Agent not connecting on Docker 20.10.21

### ISSUE THREAD

**Issue by gseqBE** [micro-ROS/micro_ros_setup#587]
- Hardware description: 
**Nucleo STM32H743zi**
- RTOS: 
**Zephyr 2.6**
- Installation type: 
**Micro_ros_setup, micro_ros_agent**
- Version or commit hash: 
**Humble**

#### Steps to reproduce the issue

- Start agent: `docker run -it --rm --net=host  microros/micro-ros-agent:humble udp4 --port 8888  -v6`
- Change IP of edge in microros_transports.h  to agent IP
- Edge shows waiting for connection.
- Wireshark shows edge requesting a connection to agent
<img width="543" alt="image" src="https://user-images.githubusercontent.com/2365134/199840443-b93a549d-bc48-4b65-b7fe-1282f9d28a4f.png">
- Agent shows:
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/2365134/199841027-b558bda8-9d0f-40b5-9ed1-b4aa1552e0ad.png">

#### Expected behavior
Agent should accept and connect to edge.

#### Actual behavior
Agent does not connect to edge.

**Comment by pablogs9** [comment]
Is 192.168.1.213 the IP of your agent?

This seems to be a network problem, not a micro-ROS problem since your micro-ROS client is sending packages correctly but they seems to not reach the agent.

**Comment by rcolatobe** [comment]
Tested configuration on a different computer and could not reproduce the actual behavior - will continue to debug networking side.
