### ISSUE TITLE
build_firmware.sh could not find a package configuration file provided by "microcdr"

### ISSUE THREAD

**Issue by Jaren-Li** [micro-ROS/micro_ros_setup#594]
## Issue template

- Hardware description: ubuntu20.04(VM)
- RTOS: host
- Installation type:  micro_ros_setup
- Version or commit hash: 

#### Steps to reproduce the issue

I followed the first micro ros application on linux as described above by micro ros.(https://micro.ros.org/docs/tutorials/core/first_application_linux/)
But soon I ran into my first problem,when I execute this instruction

`ros2 run micro_ros_setup create_firmware_ws.sh host`

Did not download a set of micro-ROS apps for Linux as described in the documentation.

Then I downloaded the missing parts myself,like the picture below
![image](https://user-images.githubusercontent.com/61934081/202248494-334d9a88-07a4-402d-b607-a9259f592446.png)
Next, execute this instruction
`ros2 run micro_ros_setup build_firmware.sh`
then
```
Compiling for host environment: not cleaning path
Building firmware for host platform generic
Starting >>> rosidl_typesupport_microxrcedds_c
--- stderr: rosidl_typesupport_microxrcedds_c
CMake Error at CMakeLists.txt:20 (find_package):
  By not providing "Findmicrocdr.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "microcdr",
  but CMake did not find one.

  Could not find a package configuration file provided by "microcdr" with any
  of the following names:

    microcdrConfig.cmake
    microcdr-config.cmake

  Add the installation prefix of "microcdr" to CMAKE_PREFIX_PATH or set
  "microcdr_DIR" to a directory containing one of the above files.  If
  "microcdr" provides a separate development package or SDK, be sure it has
  been installed.


---
Failed   <<< rosidl_typesupport_microxrcedds_c [0.80s, exited with code 1]

Summary: 0 packages finished [1.48s]
  1 package failed: rosidl_typesupport_microxrcedds_c
  1 package had stderr output: rosidl_typesupport_microxrcedds_c

```
#### Expected behavior
It should download normally
#### Actual behavior
No normal download
#### Additional information
I'm not sure if there is anything missing in the src folder.
I hope you can help me solve this problem,thanks.

**Comment by Acuadros95** [comment]
The error is related to the manual download of sources, just follow the instructions and everything should run smoothly.

> Did not download a set of micro-ROS apps for Linux as described in the documentation.

Double check this, as the apps are under the directory `src/uros/micro-ROS-demos`.
