### ISSUE TITLE
I have a problem when installing the marlin in the artillery genius pro Visual Studio

### ISSUE THREAD

**Issue by TomasLedesma00** [micro-ROS/micro_ros_setup#596]
## Issue template

- Hardware description:  Artillery Genius Pro
- RTOS: 
- Installation type:  Visual Studio
- Version or commit hash:   Marlin Version 2.0.x

#### Steps to reproduce the issue
 
Hello good evening, first of all sorry for my English.

I tell you my problem, I am trying to install the marlin in the genius but when uploading I get the following error 

#### Actual behavior

embedded:startup.tcl:26: Error: Can't find scripts/interface/stlink.cfg
in procedure 'script'
at file "embedded:startup.tcl", line 26
*** [upload] Error 1

#### Additional information

When building the marlin, it does it perfectly, only the error appears when I want to install it on the printer. I already tried with other versions of Marlin and the same thing happens. So also with another version of Pio and AutoBuildMarlin

If you could help me more than grateful

**Comment by pablogs9** [comment]
Not a micro-ROS issue. I think you got the repository wrong
