### ISSUE TITLE
micro-ROS adding new firmware workspace 

### ISSUE THREAD

**Issue by michaell12** [micro-ROS/micro_ros_setup#598]
Hey, i tried to make a first micro-ROS app on freeRTOS using the tutorial here:
https://micro.ros.org/docs/tutorials/core/first_application_rtos/freertos/
I'm using Ultra96 v1 board with microblaze microprocessor. i saw the board is supported in FreeRTOS website.
During the micro-ROS app on freeRTOS tutorial, they are using stm32 board and im using a different one.
during the creating a new firmware workspace, i need a different platform from what the micro ros setup has.
![image](https://user-images.githubusercontent.com/20728363/205437032-d20b718a-9f5e-405b-b174-5c0ff3b80b6c.png)

how do i add a new platform to work with? or make the right adaptions to my hardware

**Comment by pablogs9** [comment]
Hello, the board you mention has no official support for micro-ROS. You have more information about porting micro-ROS here:https://docs.vulcanexus.org/en/latest/rst/tutorials/micro/custom_platforms/custom_platforms.html

In case you need professional support please contact support@eProsima.com
