### ISSUE TITLE
A fatal error occurred: Could not open /dev/ttyUSB0, the port doesn't exist 

### ISSUE THREAD

**Issue by hanselhermawan** [micro-ROS/micro_ros_setup#599]
## Issue template

- Hardware description: ESP 32

I tried to compile the IDE into ESP32 but there is a problem like this 

![Screenshot from 2022-12-10 15-53-11](https://user-images.githubusercontent.com/117617089/206842059-27168088-9306-4ee9-bbca-8adfd5bb304d.png)

can anyone help me ?

**Comment by pablogs9** [comment]
Not related to micro-ROS
