### ISSUE TITLE
Issue while increasing the data size more than 495 Bytes for Best-effort stream 

### ISSUE THREAD

**Issue by SiddharthZokarkar** [micro-ROS/micro_ros_setup#620]
- Hardware description: ESP32 
- RTOS: FreeRTOS
- Installation type: micro_ros_setup
- Version:  micro-ROS running on ROS2 Foxy

Hello

I am using best-effort stream communication for publisher and subscriber. 

The publisher and subscriber are working fine for data upto 495 Bytes. 

But after increasing the data over 495 Bytes, the publisher is not publishing the topic data (although it is showing the published topic name in ros2 topic list) and the subscriber is showing a **serialization error** as shown in the below picture.

![Serialisation error best effort stream](https://user-images.githubusercontent.com/117823409/226358172-dea88b80-a2c2-4c8d-a15e-2b9bebb6e3b5.png)

 **app-colcon.meta** 

![app-colcon meta](https://user-images.githubusercontent.com/117823409/226386476-a94b4637-ef44-4284-a84a-17cd1179a17c.png)

I am not able to understand the problem . It will be great if anyone can help me to figure out the problem.

Thank you very much!!

**Comment by SiddharthZokarkar** [comment]
Hello @pablogs9 ,

I am struggling to increase the data length using Best-effort stream over 495 Bytes.  Is that a limit ? Or is there any way to increase the size?

Kindly give your suggestions.
Thank you so much.

**Comment by Acuadros95** [comment]
Hi @SiddharthZokarkar,

In this case the transport used is `custom`, as the provided configurations (`udp`, `serial`, ...) are used only for linux builds.
Rebuild your micro-ROS library using the following configuration parameter: `UCLIENT_PROFILE_CUSTOM_TRANSPORT`

**Comment by SiddharthZokarkar** [comment]
Hello @Acuadros95 ,

Thanks for the reply.  I am using inbuild Serial transport on a Linux system instead of a custom transport.  
What is the procedure to increase the data size more than 495 Bytes?

I tried by changing   UCLIENT_SERIAL_TRANSPORT_MTU 4096  but it is not working.

Kindly guide me. 
Thanks

**Comment by Acuadros95** [comment]
> I tried by changing UCLIENT_SERIAL_TRANSPORT_MTU 4096 but it is not working.

You need to use the `UCLIENT_PROFILE_CUSTOM_TRANSPORT` parameter instead of the Serial one.

**Comment by SiddharthZokarkar** [comment]
Ok thank you so much!!
