### ISSUE TITLE
Using Ethernet on a STM32 board.

### ISSUE THREAD

**Issue by mstiehm-NF** [micro-ROS/micro_ros_setup#627]
Looking through the cmake.in and Makefile of the Olimex E407, I found that the setup is very similar to the F746ZG borard I am trying to use. 

I modified the cmake and Makefile to include the POSIX sources that were missing in the F746zg project and I am able to compile and run the int32_publisher app, but when calling `rclc_support_init()`, the program hangs. I use wireshark and I see that the board arps the correct IP address, but no other packets are sent.

I am wondering if there is a way to debug into the rclc functions? I am unable to step into them because we include the static library instead of all the individual source files

**Comment by Acuadros95** [comment]
> From what I can tell, the Olimex uses the lwip library and does not implement custom transports for UDP.

You are right. For reference, this is the transport used with the approach you are following: [udp_transport_posix_nopoll.c](https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/master/src/c/profile/transport/ip/udp/udp_transport_posix_nopoll.c).

My recommendation is to use the [micro_ros_stm32cubemx_utils](https://github.com/micro-ROS/micro_ros_stm32cubemx_utils) approach and try to implement your own custom transport and debug it using CubeIDE.
