### ISSUE TITLE
Micro_ros udp transport build issue on esp32

### ISSUE THREAD

**Issue by Apurva2510** [micro-ROS/micro_ros_setup#631]
## Issue template

- Hardware description: esp-wroom-32
- RTOS: freertos
- Installation type: micro_ros_setup
- Version or commit hash: humble

#### Steps to reproduce the issue
ros2 run micro_ros_setup configure_firmware.sh motor_subscriber -t udp -i [YOUR IP] -p 8888

ros2 run micro_ros_setup build_firmware.sh

#### Expected behavior
100% build

#### Actual behavior
![Screenshot from 2023-04-14 12-03-34](https://user-images.githubusercontent.com/122956270/231962121-b5f39012-880d-439c-a85b-77ee20086323.png)

#### Additional information
When I try to build it with serial Transport the build is successful with some stderr outputs but when I try udp it does not seem to build

**Comment by pablogs9** [comment]
Hello @Apurva2510 the recommended approach for using micro-ROS in ESP32 is using the component for ESP-IDF. Could you give a try using this repo: https://github.com/micro-ROS/micro_ros_espidf_component

**Comment by Apurva2510** [comment]
> Hello @Apurva2510 the recommended approach for using micro-ROS in ESP32 is using the component for ESP-IDF. Could you give a try using this repo: https://github.com/micro-ROS/micro_ros_espidf_component

@pablogs9 OK. I will try that approach.

**Comment by Apurva2510** [comment]
Update: @pablogs9 The repo that you mentioned worked for the udp transport. Thanks a lot for that advise!

**Comment by Acuadros95** [comment]
Closing as its solved
