### ISSUE TITLE
A microcontroller which both supports micro-ROS and 1000/10000 mbps Ethernet 

### ISSUE THREAD

**Issue by MertAdak** [micro-ROS/micro_ros_setup#632]
Hello,

I need a microcontroller which both supports micro-ROS and ethernet speed of 1000/10000 mbps. Is there any microcontroller that you know for this purpose?

Thank you,
Mert Adak

**Comment by pablogs9** [comment]
Hello @MertAdak, sorry but we cannot help you here as this is not a micro-ROS issue. Please feel free to use the ROS 2 forums or the micro-ROS slack.
