### ISSUE TITLE
How to use Ethernet transport in micro-ROS running on ESP32?

### ISSUE THREAD

**Issue by vijhu** [micro-ROS/micro_ros_setup#650]
- Hardware description: ESP32
- RTOS: FreeRTOS
- Installation type: micro_ros_setup
- Version - micro-ROS running on ROS2 Foxy

Hello @pablogs9 ,

I am trying to use Ethernet transport in micro-ROS on  ESP32 microcontroller. 

I am not able to find any steps how to configure the Ethernet.

I found this command: 
ros2 run micro_ros_setup configure_firmware.sh [PROJECT NAME] -t udp -i [LOCAL MACHINE IP ADDRESS] -p 8888
ros2 run micro_ros_setup build_firmware.sh menuconfig

But these are to configure using WIFI. Do I need to use some different commands?

The micro-ROS is running on LINUX enviroment.

It will be a great help if you can just provide the steps for the ethernet configuration.

Thank you in advance!!

**Comment by pablogs9** [comment]
Hello, Ethernet is not supported by this package and ESP32.

**Comment by vijhu** [comment]
Ok means a custom transport for ethernet need to be made. Thank you so much!!
