### ISSUE TITLE
create_firmware_ws.sh ERROR - the following packages/stacks could not have their rosdep keys resolved to system dependencies

### ISSUE THREAD

**Issue by Alexios567** [micro-ROS/micro_ros_setup#652]
## Issue template

- Hardware description: 
- RTOS: 
- Installation type: 
- Version or commit hash: 

#### Steps to reproduce the issue

when run `ros2 run micro_ros_setup create_firmware_ws.sh freertos esp32 `
ERROR

#### Actual behavior
`Done! You can now compile ESP-IDF projects.
Go to the project directory and run:

  idf.py build

Collecting catkin_pkg
  Using cached catkin_pkg-0.5.2-py3-none-any.whl (76 kB)
Collecting lark-parser
  Using cached lark_parser-0.12.0-py2.py3-none-any.whl (103 kB)
Collecting empy
  Using cached empy-3.3.4-py3-none-any.whl
Collecting docutils (from catkin_pkg)
  Using cached docutils-0.20.1-py3-none-any.whl (572 kB)
Collecting python-dateutil (from catkin_pkg)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Requirement already satisfied: pyparsing in ./espressif/python_env/idf4.1_py3.8_env/lib/python3.8/site-packages (from catkin_pkg) (2.3.1)
Requirement already satisfied: setuptools in ./espressif/python_env/idf4.1_py3.8_env/lib/python3.8/site-packages (from catkin_pkg) (67.8.0)
Collecting six>=1.5 (from python-dateutil->catkin_pkg)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: lark-parser, empy, six, docutils, python-dateutil, catkin_pkg
Successfully installed catkin_pkg-0.5.2 docutils-0.20.1 empy-3.3.4 lark-parser-0.12.0 python-dateutil-2.8.2 six-1.16.0

ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
rclc_parameter: Cannot locate rosdep definition for [osrf_testing_tools_cpp]
rcl_logging_noop: Cannot locate rosdep definition for [launch_testing]
rosidl_typesupport_c: Cannot locate rosdep definition for [rcpputils]
tracetools_test: Cannot locate rosdep definition for [rclcpp]
ros2trace: Cannot locate rosdep definition for [ros2cli]
rcl: Cannot locate rosdep definition for [rcl_yaml_param_parser]
rcl_lifecycle: Cannot locate rosdep definition for [osrf_testing_tools_cpp]
rclc: Cannot locate rosdep definition for [osrf_testing_tools_cpp]
rosidl_typesupport_cpp: Cannot locate rosdep definition for [rcpputils]
rclc_lifecycle: Cannot locate rosdep definition for [osrf_testing_tools_cpp]
rmw: Cannot locate rosdep definition for [osrf_testing_tools_cpp]
rosidl_default_generators: Cannot locate rosdep definition for [rosidl_typesupport_introspection_cpp]
rosidl_default_runtime: Cannot locate rosdep definition for [rosidl_typesupport_introspection_cpp]
rmw_implementation: Cannot locate rosdep definition for [rcpputils]
rcutils: Cannot locate rosdep definition for [osrf_testing_tools_cpp]
tracetools_launch: Cannot locate rosdep definition for [launch_ros]
libyaml_vendor: Cannot locate rosdep definition for [rcpputils]
rosidl_typesupport_microxrcedds_c_tests: Cannot locate rosdep definition for [rosidl_typesupport_introspection_c]
test_rmw_implementation: Cannot locate rosdep definition for [rmw_dds_common]
rcl_action: Cannot locate rosdep definition for [osrf_testing_tools_cpp]`

**Comment by Acuadros95** [comment]
Closing, as we could not replicate your error on a fresh `ros:humble` docker.

Anyway, we recommend to use the alternative [micro-ROS component for ESP-IDF](https://github.com/micro-ROS/micro_ros_espidf_component) build system, as we have plans to deprecate micro-ROS setup.
