### ISSUE TITLE
Pip dependencies error while running Zephyr Emulator tutorial

### ISSUE THREAD

**Issue by arnixrobotix** [micro-ROS/micro_ros_setup#681]
I am trying to run the Zephyr emulator tutorial in a VS code's dev container using a ros:humble image.

#### Steps to reproduce the issue

I cloned the Micro-ROS setup repo and launched the dev container which is running rosdep and building the initial workspace.

#### Expected behavior
Create step is effectively creating the firmware folder.

#### Actual behavior
The create step yields the following error (when running `pip install --force-reinstall Sphinx==4.2.0` ): 
```
    ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
    sphinx-tabs 3.2.0 requires docutils~=0.16.0, but you have docutils 0.17.1 which is incompatible.
    sphinx-rtd-theme 0.5.2 requires docutils<0.17, but you have docutils 0.17.1 which is incompatible.
```

#### Additional information
It looks like the conflicts are coming from `firmware/zephyrproject/zephyr/scripts/requirements-doc.txt` where specified sphinx version is 3.*

**Comment by pablogs9** [comment]
Please move to https://github.com/micro-ROS/micro_ros_zephyr_module

**Comment by arnixrobotix** [comment]
Created an issue in Zephyr module repo.
