### ISSUE TITLE
ROS2 Jazzy version release

### ISSUE THREAD

**Issue by logicraju** [micro-ROS/micro_ros_setup#693]
## Issue template

- Hardware description: RPi 5
- OS: Ubuntu 24.04 LTS
- ROS2 Version: Jazzy Jalisco

#### Steps to reproduce the issue
git clone -b $ROS_DISTRO https://github.com/micro-ROS/micro_ros_setup.git src/micro_ros_setup

#### Expected behavior
Install micro ros

#### Actual behavior
fatal: Remote branch jazzy not found in upstream origin

#### Additional information
When is Jazzy version going to be released ?

**Comment by pablogs9** [comment]
We plan to start the micro-ROS release for Jazzy next week.
