### ISSUE TITLE
Remove branch feature/mempools_refactor and  crazyflie_demo

### ISSUE THREAD

**Issue by pablogs9** [micro-ROS/micro_ros_setup#93]
Are we ok with removing the following branch:
 - [x]  https://github.com/micro-ROS/micro-ros-build/tree/feature/mempools_refactor
 - [x]  https://github.com/micro-ROS/micro-ros-build/tree/crazyflie_demo

The last one is related to https://micro-ros.github.io/docs/tutorials/demos/crazyflie_demo/. Are you going to replace this tutorial with the new approach based on https://github.com/micro-ROS/micro-ROS_crazyflie_demo @jfm92 ?

**Comment by pablogs9** [comment]
@Acuadros95 check if we can close this when you are done with the demo.

**Comment by Acuadros95** [comment]
Yes, https://github.com/micro-ROS/micro-ros-build/tree/crazyflie_demo can be safely removed.
